charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/templates/_config.tpl
move `exporters` and `service.pipelines` into if statement to avoid
setting them to null when standalone is disabled
Signed-off-by: naseemkullah <naseem@transit.app>
=> fix: agent default config override template

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/templates/_config.tpl
When enabling the standalone collector, the chart wires the agent's OTLP exporter to the standalone collector at the [legacy port](https://github.com/open-telemetry/opentelemetry-collector/blob/88ab1a6fd923010b1397edb38fbd01375531e3bb/receiver/otlpreceiver/otlp.go#L129-L140).
It didn't work because the `service` of the standalone collector [only listens](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/3057edf2d973b0268ec82ffe92857a6b9926f8bb/charts/opentelemetry-collector/values.yaml#L101-L106) on the correct port (4317).
=> fix: agent collector using the legacy gRPC port

charts/opentelemetry-collector/Chart.yaml
Following [the 0.20.0 release](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.20.0) from a week ago.
=> chore: update otel-collector to 0.20.0

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/templates/_config.tpl
Starting from helm 3.5.0, merging rules were changed: now if null value merged into a dict, null value is preserved.
In order to make it cleaner and working across all helm versions, this commit replaces the merge operation with a conditional set.
If user wants to override the default memory_limiter configuration, they should override all the fields. That behavior seems more practical than partial override for the this processor.
Resolves https://github.com/open-telemetry/opentelemetry-helm-charts/issues/34
=> Fix default memory_limiter configuration for helm version 3.5.x

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/templates/_pod.tpl, charts/opentelemetry-collector/values.yaml
Adds the ability for people to mount secrets. This can be used for referencing certificates in the config, like so:
```
secretMounts:
- name: jaeger-cert
secretName: jaeger-cert
mountPath: /etc/tls
readOnly: true
subPath: jaeger # subPath is optional
```
```
exporters:
jaeger:
endpoint: localhost
cert_file: /etc/tls/tls.crt
key_file: /etc/tls/tls.key
```
=> implement secret mounting

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/templates/_pod.tpl, charts/opentelemetry-collector/values.yaml
This PR would add the ability to mount extra ConfigMaps by setting the `extraConfigMapMounts` value.
Values set example:
```yaml
standaloneCollector:
enabled: true
configOverride:
receivers:
jaeger:
protocols:
grpc:
remote_sampling:
strategy_file: "/conf/jaeger/strategies.json"
extraConfigMapMounts:
- name: jaeger-sampling-strategies
configMap: jaeger-sampling-strategies
mountPath: /conf/jaeger
readOnly: true
```
Extra ConfigMap example:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: jaeger-sampling-strategies
data:
strategies.json: |-
{
"default_strategy":
{
"type": "probabilistic",
"param": 1
}
}
```
=> Add ability to mount extra ConfigMaps to OTel collector pods

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/templates/_pod.tpl, charts/opentelemetry-collector/values.yaml
This will add the ability to set a priorityClassName as part of the deployment.
The Deployment for the agents can be set to a higher priority to make sure the scheduler deploys the agents first before any apps are deployed.
=> Added priorityClassName to pod template and values file

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/templates/service.yaml
Currently the ServiceMonitor fails to capture the prometheus metrics exposed by the collector when deploying in standalone mode due to the absence of the label `component: standalone-collector`.
Current ServiceMonitor selector (version 0.5.6)
```
selector:
matchLabels:
app.kubernetes.io/instance: opentelemetry-collector
app.kubernetes.io/name: opentelemetry-collector
component: standalone-collector
```
service labels:
```
labels:
app.kubernetes.io/instance: opentelemetry-collector
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: opentelemetry-collector
app.kubernetes.io/version: 0.22.0
helm.sh/chart: opentelemetry-collector-0.5.6
```
This PR adds the missing label to the service so that the metrics can be properly scraped by prom operator
=> Add missing label to service for ServiceMonitor

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/templates/deployment.yaml, charts/opentelemetry-collector/values.yaml
This provides the ability to add arbitrary deployment annotations when using the standalone collector. This will enable the use of any operators that rely on deployment annotations.
Example for wave config reloading:
```yaml
standaloneCollector:
enabled: true
replicaCount: 1
resources:
limits:
cpu: 1
memory: 2Gi
podAnnotations: {}
annotations:
wave.pusher.com/update-on-config-change: "true"
```
=> add annotations to deployment for standalone collector

.github/workflows/lint-test.yaml, charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/release/kuttl-test.yaml, charts/opentelemetry-operator/release/release-checklist.md
**Description**
Currently, during every release of the Operator Helm chart, maintainers need to clone the operator repo and run the KUTTL tests locally. This PR migrates the KUTTL tests to Github workflow so that the tests will run automatically when a new PR is submitted.
**Related Issue**
#57
cc @alolita @dmitryax @tigrannajaryan
=> Migrate Operator Helm chart KUTTL tests to Github workflow

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
These fields don't appear to be valid per the [CustomResourceDefinition Spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#customresourcedefinitionspec-v1-apiextensions-k8s-io)
=> Remove invalid crd fields

.github/workflows/release.yaml
The newer version fixes the issue with v1.1.0 - see https://github.com/helm/chart-releaser-action/issues/61
Fixes #72 
(Note: It may be necessary to push a version change to get it to detect previously merged changes)
=> Upgrade releaser version

charts/opentelemetry-operator/Chart.yaml
Related to #72 and #74 - the releaser update wasn't enough on its own because it was comparing to the failed release.
=> Bump chart version

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/templates/service.yaml, charts/opentelemetry-collector/values.yaml
Defined configuration for headless service in open-telemetry helm charts. 
This allows us to directly interact with PODs instead of proxy.
Co-authored-by: Betsy Behun <betsybehun@gmail.com>
closes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/61
=> Defined configuration for headless service

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/templates/hpa.yaml
A current issue between ArgoCD (https://github.com/argoproj/argo-cd/issues/1079) and Kubernetes (https://github.com/kubernetes/kubernetes/issues/74099) makes the HPA stay constantly out of sync. This affects Gitops pipelines when both memory and CPU metrics are used to autoscale the deployment.
This change reorders HPA metrics to make sure that they remain in the order that the Kubernetes HPA controller currently expects them to be.
=> Reorder opentelemetry-collector HPA metrics

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/templates/deployment.yaml, charts/opentelemetry-operator/values.yaml
This PR addresses #111 and adds the functionality to set the default Collector image through the Operator helm chart if the user explicitly configures it. Otherwise, the behavior of the chart is unchanged.
To set the default Collector image, you must `--set` a repository (`manager.collectorImage.repository`) and a tag (`manager.collectorImage.tag`) when you run the `helm install` command.
=> Add `--otelcol-image` CLI Flag to Operator Helm Chart

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/templates/deployment.yaml
This PR is a minor fix to #113 and removes extra quotation marks in the CLI flag in `deployment.yaml`.
=> Minor Fix to `--otelcol-image` CLI Flag

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/templates/pdb.yaml, charts/opentelemetry-collector/values.yaml
By default, you can only have one or the other. If both are set then we get the following error: 
```
EXIT STATUS
1
COMBINED OUTPUT:
Error: UPGRADE FAILED: release opentelemetry-collector failed, and has been rolled back due to atomic being set: failed to create resource: PodDisruptionBudget.policy "opentelemetry-collector" is invalid: spec: Invalid value: policy.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0xc045b8be40), Selector:(*v1.LabelSelector)(0xc045b8be60), MaxUnavailable:(*intstr.IntOrString)(0xc045b8be20)}: minAvailable and maxUnavailable cannot be both set
```
=> Update podDisruptionBudget default values

.github/workflows/lint-test.yaml, charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/README.md, charts/opentelemetry-operator/release/release-checklist.md, charts/opentelemetry-operator/templates/_helpers.tpl, charts/opentelemetry-operator/templates/admission-webhooks/mutatingwebhookconfiguration.yaml, charts/opentelemetry-operator/templates/admission-webhooks/validatingwebhookconfiguration.yaml, charts/opentelemetry-operator/templates/certmanager.yaml, charts/opentelemetry-operator/templates/clusterrolebinding.yaml, charts/opentelemetry-operator/templates/deployment.yaml, charts/opentelemetry-operator/templates/namespace.yaml, charts/opentelemetry-operator/templates/role.yaml, charts/opentelemetry-operator/templates/rolebinding.yaml, charts/opentelemetry-operator/templates/service.yaml, charts/opentelemetry-operator/templates/serviceaccount.yaml, charts/opentelemetry-operator/values.yaml
As mentioned in #73 it is rather unusual for a chart to both 1) Automatically create the install namespace; and 2) Not allow changing the install namespace.
In my experience it is more idiomatic in Helm to control the install namespace by specifying the `--namespace` helm flag.
This PR:
- Removes the namespace auto-create functionality
- Removes the hardcoded namespace name and;
- Uses `{{ .Release.Namespace }}` for `metadata.namespace` and related references
Fixes #73
=> Allow user-defined install namespace for operator

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/values.yaml
The metrics port is not declared, not sure what the reason is for that.
Declare metrics port by default.
=> declare metrics port by default

.github/workflows/lint-test.yaml
Fixes #126 
Today the lint-test workflow runs the operator e2e tests against latest.  This can cause problem if the operator latest is ahead of the chart's target version.  This change updates the lint-test workflow to always run the operator e2e tests against the operator version that matches appVersion.
=> Update operator e2e tests to always run against appVersion

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/templates/deployment.yaml
It looks like the underlying operator image was updated to accept the flag `--collector-image` instead of `--otelcol-image` (which we currently set).
See https://github.com/open-telemetry/opentelemetry-operator/blob/7101339a6b346ec929e81cacfdbd270f04824356/main.go#L87
This updates the Chart to set the correct flag
=> Fix: use --collector-image instead of --otelcol-image

charts/opentelemetry-collector/Chart.yaml
Updated appVersion to 0.46.0 so that the default image version will be 0.46.0.  Reviewing the Core and Contrib change log and release notes I didn't see anything that would affect the charts.  Let me know if there is something I missed.
=> Increase default image version to 0.46.0

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml, charts/opentelemetry-operator/crds/crd-opentelemetryinstrumentation.yaml, charts/opentelemetry-operator/values.yaml
diff `opentelemetry-operator.yaml` between v0.43.0 and v0.45.0
```
>     - jsonPath: .spec.exporter.endpoint
>       name: Endpoint
>       type: string
>     - jsonPath: .spec.sampler.type
>       name: Sampler
>       type: string
>     - jsonPath: .spec.sampler.argument
>       name: Sampler Arg
>       type: string
2092c2101
<                 description: Messages about actions performed by the operator on this resource.
---
>                 description: 'Messages about actions performed by the operator on this resource. Deprecated: use Kubernetes events instead.'
2468c2477
<         image: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.43.0
---
>         image: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.45.0
```
=> Update OTEL Operator to v0.45.0 release

README.md, artifacthub-repo.yml
Provide integration with Artifact Hub so that Helm charts are discoverable there.
I have already created and configured an organization on Artifact Hub and configured it so that it will be [a verified publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher).
Once things are merged, you can apply to [claim official status](https://artifacthub.io/docs/topics/repositories/#official-status).
Outcome: https://artifacthub.io/packages/search?repo=opentelemetry-helm&sort=relevance&page=1
Relates to https://github.com/open-telemetry/opentelemetry-helm-charts/issues/108
=> feat: Provide integration with Artifact Hub

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/values.schema.json
The helm chart with 0.9.4 set `additionalProperties` to false in `values.schema.json`.
Depending on the helm version used the chart fails to be deployed with the following error message:
\- (root): Additional property global is not allowed
There is also an issue already in the helm repository:
https://github.com/helm/helm/issues/10392
Current established workaround is to add global to the allowed properties or set additionalProperties to true. I choose the first possibility
=> collector chart 0.9.4 cannot be deployed with some helm versions

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/templates/_helpers.tpl, charts/opentelemetry-operator/templates/deployment.yaml, charts/opentelemetry-operator/values.yaml
This PR adds support for configuration of additional environment variables needed  to configure Opentelemetry-Operator Manager. Thanks to that `WATCH_NAMESPACE` variable can be configured during chart deployment.
Functionality:
- If `values.manager.env` is empty then `env` is not added to the manager deployment (default)
- If `values.manager.env` contains map (KEY: value) then it's added to the manager deployment as k8s env obj
=> feat: support environment variables in manager

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml, charts/opentelemetry-operator/templates/clusterrole.yaml, charts/opentelemetry-operator/values.yaml
diff opentelemetry-operator.yaml between v0.45.0 and v0.46.0
```
644a645,648
>               maxReplicas:
>                 description: MaxReplicas sets an upper bound to the autoscaling feature. If MaxReplicas is set autoscaling is enabled.
>                 format: int32
>                 type: integer
2275a2280,2291
>   - autoscaling
>   resources:
>   - horizontalpodautoscalers
>   verbs:
>   - create
>   - delete
>   - get
>   - list
>   - patch
>   - update
>   - watch
> - apiGroups:
2477c2493
<         image: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.45.0
---
>         image: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator:v0.46.0
```
=> Update OTEL Operator to v0.46.0 release

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/templates/NOTES.txt, charts/opentelemetry-collector/templates/_pod.tpl, charts/opentelemetry-collector/values.schema.json, charts/opentelemetry-collector/values.yaml
This PR adds new `extraVolumes` and `extraVolumeMounts` variable and deprecates `extraConfigMapMounts`, `extraHostPathMounts`, and `secretMounts`.  
Going forward, `extraVolumes` and `extraVolumeMounts` will allow more flexible `volumes` and `volumeMounts` by putting the configuration in the hands of the user.
Fixes #133
=> Added more flexible volume variables

charts/opentelemetry-collector/Chart.yaml
This PR updates the default collector image version to 0.47.0.  Reviewing opentelemetry-collector and opentelemetry-collector-contrib I see no breaking changes that will affect the chart configuration.
Fixes #153
=> Updated default image to 0.47.0

README.md
Propose to add @TylerHelmuth as an approver in this repository.
Tyler is helping a lot with solving issues in this repo. 
He submitted and reviewed the following PRs:
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/129
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/131
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/139
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/147
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/151
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/142
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/143
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/148
cc @open-telemetry/helm-approvers
=> Add Tyler Helmuth as an approver

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/examples/agent-and-standalone/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/agent-and-standalone/rendered/configmap.yaml, charts/opentelemetry-collector/examples/agent-and-standalone/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/agent-and-standalone/rendered/deployment.yaml, charts/opentelemetry-collector/examples/agent-and-standalone/rendered/service.yaml, charts/opentelemetry-collector/examples/agent-and-standalone/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/agent-only/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/agent-only/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/agent-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/standalone-only/rendered/configmap.yaml, charts/opentelemetry-collector/examples/standalone-only/rendered/deployment.yaml, charts/opentelemetry-collector/examples/standalone-only/rendered/service.yaml, charts/opentelemetry-collector/examples/standalone-only/rendered/serviceaccount.yaml
This PR updates the default collector image version to 0.48.0. Reviewing opentelemetry-collector and opentelemetry-collector-contrib I see no breaking changes that will affect the chart configuration.
Fixes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/160
=> Updated default collector version to 0.48.0

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/examples/agent-and-standalone/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/agent-and-standalone/rendered/configmap.yaml, charts/opentelemetry-collector/examples/agent-and-standalone/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/agent-and-standalone/rendered/deployment.yaml, charts/opentelemetry-collector/examples/agent-and-standalone/rendered/service.yaml, charts/opentelemetry-collector/examples/agent-and-standalone/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/agent-only/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/agent-only/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/agent-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/standalone-only/rendered/configmap.yaml, charts/opentelemetry-collector/examples/standalone-only/rendered/deployment.yaml, charts/opentelemetry-collector/examples/standalone-only/rendered/service.yaml, charts/opentelemetry-collector/examples/standalone-only/rendered/serviceaccount.yaml
Release 0.13.0 did not work properly.  Bumping patch version to force new release.  Related to https://github.com/open-telemetry/opentelemetry-helm-charts/pull/161
=> Bump version to force release.

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-only/values.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml, charts/opentelemetry-collector/templates/_config.tpl, charts/opentelemetry-collector/templates/deployment.yaml
This PR fixes a variable assignment issue in the deployment.yaml template where the root-level configs such as `replicaCount` and `resource.limits` where not used correctly when `mode` was set to `deployment`.  
I updated the `deployment-only` example to set some root-level configs to prove it is working correctly now.
I also check all occurrences of the `if eq .Values.mode` pattern and they all now use `=` instead of `:=`
Fixes #170
=> Fixes issue where deployment root-level configuration was not overriding standaloneCollector config

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml
This PR updates the default collector image version to 0.49.0. Reviewing opentelemetry-collector and opentelemetry-collector-contrib I see no breaking changes that will affect the chart configuration.
Fixes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/168
=> Updated default collector version to 0.49.0

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/templates/deployment.yaml
Use [kubectl well-known annotation](https://github.com/paulfantom/opentelemetry-helm-charts/pull/new/default-container) to define default container in a pod. This simplifies operations like getting logs from a container as seen below:
```shell
kubectl logs opentelemetry-operator-controller-manager-5d47c94d97-w7xs9 -c manager
kubectl logs opentelemetry-operator-controller-manager-5d47c94d97-w7xs9
```
=> charts/opentelemetry-operator: define default container

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/README.md
This PR updates the sidecar example in the Operator README, as it does not work. It changes the `jaegerreceiver` protocol to `thrift_compact` instead of `grpc`. This is also reflected in a PR on the `opentelemetry-operator` repository, [837](https://github.com/open-telemetry/opentelemetry-operator/pull/837).
=> Update sidecar example in Operator README

.github/actions/setup/action.yaml, .github/workflows/collector-test.yaml, .github/workflows/lint.yaml, .github/workflows/operator-test.yaml
This PR breaks our collector and operator specific tests into their own workflows.  Setup steps are moved to a composite action so they can be used across the 3 different workflows.  The collector and operator workflows are only run when files in the chart have been changed.
After this change the integration tests will run regardless of whether or not the chart passes linting, but all existing lint checks are still applied via the lint workflow.  This will allow the charts to be tested even if they aren't passing the lint test, but also the PR will not be completable until linting also passes.
Fixes #179
=> Break out collector and operator specific tests

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml, charts/opentelemetry-collector/templates/daemonset.yaml, charts/opentelemetry-collector/values.schema.json, charts/opentelemetry-collector/values.yaml
There is a need to specify the dnsPolicy of the daemonset pods such as ClusterFirstWithHostNet when the host network is shared. Here is a PR implementing this scenario.
=> add dnsPolicy to daemonset pods

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/values.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml
This PR updates the default collector image version to 0.50.0. Reviewing opentelemetry-collector and opentelemetry-collector-contrib I see no breaking changes that will affect the chart configuration.
Fixes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/194
=> Updated default collector version to 0.50.0

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/values.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml
Currently the collector logs example configures the file log receiver, but doesn't add it to the pipeline.  This PR updates the example's values.yaml to list filelog in the log pipeline's receivers.
This issue arose from the `mode` refactor, where `.Values.config` needed to be applied after all other configuration.  In doing so, the default logs pipeline in `.Values.config` is [overwriting the list from the containerLog preset](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/f811817298ea434074d0457d68d7b4dfd4b50f7a/charts/opentelemetry-collector/templates/_config.tpl#L194).  
This is the same issue we've been discussing in #158 around presets and custom config.  Luckily, the proposal in #158 will do away with any default values in `.Values.config`.  If there is no …
=> Fix collector-logs example

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml, charts/opentelemetry-collector/templates/_config.tpl
Fixes #204
This PR removes a move command for the `run_id` attribute from the default `filelog` receiver config.
=> Remove move statement for run id

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml
This PR updates the default collector image version to 0.51.0. Reviewing opentelemetry-collector and opentelemetry-collector-contrib I see no breaking changes that will affect the chart configuration.  [There was an update to the filelog receiver k8s example to fix native OTel logs collection issue where 0 length logs cause errors](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/9754), but our filelog receiver template already has the correct regex.
Fixes #209
=> Updated default collector version to 0.51.0

.github/workflows/operator-test.yaml, charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml, charts/opentelemetry-operator/values.yaml
Update of the OpenTelemetry Operator to [v0.51.0](https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.51.0)
=> chore(ot-operator): update version to v0.51.0

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml
This PR updates the default collector image version to 0.53.0.  Taking a look at the opentelemetry-collector and opentelemetry-collector-config changes for 0.51.0 and 0.52.0, It does not appear that there are any breaking changes.
Fixes:  https://github.com/open-telemetry/opentelemetry-helm-charts/issues/225
=> Update default opentelemetry-collector version to 0.53.0

.github/workflows/operator-test.yaml, charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml, charts/opentelemetry-operator/values.yaml
This PR updates the OTEL operator the [latest v0.53.0 release](https://github.com/open-telemetry/opentelemetry-operator/pull/927)
closes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/227
=> chore Update OTEL Operator to v0.53.0 release

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/release/go.mod, charts/opentelemetry-operator/release/go.sum
Replaces https://github.com/open-telemetry/opentelemetry-helm-charts/pull/221
=> operator: upgrade go dependancies in release module

README.md
Tyler has been doing most of the work for this repository within last several months:
- reviewed most of the PRs
- did a massive refactoring of the Collector helm chart https://github.com/open-telemetry/opentelemetry-helm-charts/issues/91
- replied to most of the issues and helped users to investigate their problems
cc @tigrannajaryan @naseemkullah
=> Promote @TylerHelmuth to maintainer role

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/templates/deployment.yaml, charts/opentelemetry-operator/templates/service.yaml, charts/opentelemetry-operator/values.yaml
This PR is related to the following issues: 
* https://github.com/open-telemetry/opentelemetry-helm-charts/issues/214
* https://github.com/open-telemetry/opentelemetry-operator/issues/896
It includes updates to the `opentelemetry-operator` chart to allow custom values to be used for ports:
```
--set manager.ports.metricsPort=8085
--set kubeRBACProxy.ports.proxyPort=8445
--set manager.ports.webhookPort=9445
--set manager.ports.healthzPort=8005
```
The default values for all these ports are the same as before and it's reflected in `values.yaml`
```yaml
manager:
ports:
metricsPort: 8080
webhookPort: 9443
healthzPort: 8081
kubeRBACProxy:
ports:
proxyPort: 8443
```
:warning: At this point, it's not going to work until PR https://github.com/open-telemetry/opentelemetry-operator/pull/899 is …
=> Added new values to allow custom ports

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml, charts/opentelemetry-collector/templates/_helpers.tpl, charts/opentelemetry-collector/templates/pdb.yaml
The `policy/v1beta1` api is deprecated as of k8s 1.22 and will be fully
removed in 1.25:
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125
The only behavior difference between the beta and v1 APIs is how empty
`spec.selector` blocks are treated, which is not applicable here.
Signed-off-by: Nathan J Mehl <n@oden.io>
=> Add helper for podDisruptionBudget API version

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/templates/deployment.yaml
It seems I managed to broke master. While testing today I get :
```Error: INSTALLATION FAILED: Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string```
This pr fixes it. 
Initial issue is https://github.com/open-telemetry/opentelemetry-helm-charts/issues/238
=> Allow operator pod to start when admissionWebhooks are disabled ADDENDUM

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/templates/deployment.yaml, charts/opentelemetry-operator/templates/service.yaml
@dmitryax @tylerbenson Split the svcmon pr into ports and svcmonitor
https://github.com/open-telemetry/opentelemetry-helm-charts/issues/252
This needs to be merged first
=> Expose metrics port in deployment/service

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml, charts/opentelemetry-operator/Chart.yaml
Opening this PR partially as a question and also as a fix, depending on the answer to the question.
Looking through the helm docs it looks to me like the maintainers list in the chart.yaml is ambiguous. It could refer only to the chart maintainers ([as with this prometheus example](https://github.com/prometheus-community/helm-charts/blob/main/PROCESSES.md#adding-chart-maintainers)) or it could refer to the chart maintainers _and_ the maintainers of the image being deployed.  
Either way, our list needs updated.  But this option should we use?  @dmitryax @Allex1 what do you think?
=> Update maintainers list in charts

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-use-existing-configMap/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-use-existing-configMap/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-use-existing-configMap/rendered/serviceaccount.yaml
The PR bumps the default collector version to 0.56.0. Reading through Contrib and Core Release notes I did not see any breaking changes.
Closes #282
=> [chore] Bump collector version

.github/workflows/demo-test.yaml, charts/opentelemetry-demo/Chart.yaml
This PR adds a new test workflow and default test scenario for the opentelemetry-demo chart.
Closes #287 
@dmitryax I agree that it is annoying to have to add a new workflow for a new chart after https://github.com/open-telemetry/opentelemetry-helm-charts/pull/181 😆
=> [opentelemetry-demo] Add test workflow and scenario for demo

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/values.schema.json
if otel demo chart become a subchart, we need add a schema to suport `enabled` and `global` value.
=> enhance otel demo chart‘s schema

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-use-existing-configMap/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-use-existing-configMap/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-use-existing-configMap/rendered/serviceaccount.yaml
The PR bumps the default collector version to 0.57.2. Reading through Contrib and Core Release notes I did not see any breaking changes.
Closes #300
=> [chore] Bump collector version to 0.57.2

Makefile
Adds opentelemetry-demo to the `CHARTS` so its examples can be generated and checked.
=> [chore] add opentelemetry-demo to example targets

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/templates/deployment.yaml
As reported on #313, the `ServiceAccountName` in the spec of the `deployment` for the Open Telemetry Operator Helm Chart is wrongly set if the user overrides the name:
If the user overrides the ServiceAccount creation for the Open Telemetry Operator in a value file like this:
```yaml
manager:
serviceAccount:
create: false
name: test
```
The ClusterRoleBinding resource is created correctly:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
labels:
app.kubernetes.io/name: opentelemetry-operator
name: opentelemetry-operator-proxy-rolebinding
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: ClusterRole
name: opentelemetry-operator-proxy-role
subjects:
- kind: ServiceAccount
name: test-controller-manager
namespace: default
```
But the `ServiceAccountName` in …
=> fix: Service Account Name for the deployment

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/templates/deployment.yaml
Following up from [here](https://cloud-native.slack.com/archives/C03HVLM8LAH/p1660146696356489) we want to make it always possible to scrape metrics of the otel operator
=> Remove conditional metrics address

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/templates/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/templates/tests/test-service-connection.yaml
Make sure the test templates sets a proper namespace to ensure easier cleanup when testing the Helm chart
=> Force namespace constraints on test manifests

charts/opentelemetry-collector/Chart.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml, charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml, charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml, charts/opentelemetry-collector/examples/deployment-use-existing-configMap/rendered/deployment.yaml, charts/opentelemetry-collector/examples/deployment-use-existing-configMap/rendered/service.yaml, charts/opentelemetry-collector/examples/deployment-use-existing-configMap/rendered/serviceaccount.yaml
The PR bumps the default collector version to 0.58.0. Reading through Contrib and Core Release notes I did not see any breaking changes.
Closes #319
=> [chore] bump collector version to 0.58.0

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/templates/_pod.tpl, charts/opentelemetry-demo/values.yaml
This PR updates the Feature flag service env vars to automatically set DATABASE_URL based on the ffs-postgres service name, which includes the release name.  If DATABASE_URL is set directly in the feature flag service's env vars it takes precedence.
Fixes #335
=> [opentelemetry-demo] Fix how DATABASE_URL gets set for Feature flag service

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/templates/_objects.tpl, charts/opentelemetry-demo/templates/_pod.tpl
Fix bug where annotation section was always rendered even if there were no annotations
=> [opentelemetry-demo] only add annotation section when required

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/templates/_pod.tpl, charts/opentelemetry-demo/values.yaml
The PR fixes the connection between the loadgenerator and the frontend as described in #358. There are 2 issues at the same time:
1. The below snippet generates environment variables for the pod containing the address of another service that it depends on. 
```
{{- if hasKey $.depends .name }}
{{- range $depend := get $.depends .name }}
- name: {{ printf "%s_ADDR" $depend | snakecase | upper }}
value: {{ printf "%s-%s:%0.f" $prefix ($depend | kebabcase) (get $.serviceMapping $depend )}}
{{- end }}
{{- end }}
```
E.g. the loadgenerator depends on the frontend and therefore `FRONTEND_ADDR: my-release-frontend:8080` is created. To reference `FRONTEND_ADDR` it must be created before the dependent environment variable. The order matters. (Source: …
=> Fix resolution of dependent environment variable.

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/templates/_pod.tpl, charts/opentelemetry-demo/templates/component.yaml
1. I removed the below comments because they are just confusing in the final template.
```
```
2. I also changed that each service only receives its own dependencies because it confused me in the first place that the complete dependency map was passed down.
=> Simplify dependency propagation

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/templates/_pod.tpl
The PR fixes #363. I.e. the email service is prefixed with http:// properly. 
Below picture shows that the order confirmations are sent properly.
@dineshg13  My datadog trial runs out in 3 days. However, I need an extension until the end of the month to present the demo. I already wrote the support without an answer yet. If you know a shortcut for an extension that does not involve speaking to a sales rep: My email for the datadog account is "nico@canida.io" 😁
=> Fix email service address

.github/workflows/release.yaml
Fixes the release workflow to work with the demo chart. Without the workaround proposed in https://github.com/helm/chart-releaser-action/issues/74 we can't release the demo due to its dependency.
=> [chore] Add dependent repositories step

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/templates/_pod.tpl, charts/opentelemetry-demo/values.schema.json, charts/opentelemetry-demo/values.yaml
This is tested and working as expected, with traces from shipping and quote services. It's a little bit kludgy to accommodate the slight variances in how each service wants the environment variables formatted w/ or w/out protocols, but it all works (even without the ffs port fix).
Fixes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/397
=> Add PHP quote service

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/values.yaml
The `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL` needs to be set to `grpc` for Elixir to send using that protocol as the default.
=> [demo] set featureflagservice traces export to grpc

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/templates/_pod.tpl
Fix email service env var: https://github.com/open-telemetry/opentelemetry-demo/blob/main/docker-compose.yml#L156.
Like all our other env var issues, this is a bandaid until I can refactor how the chart handles env vars
=> Fix email service env var

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/templates/_pod.tpl, charts/opentelemetry-demo/templates/component.yaml, charts/opentelemetry-demo/values.yaml
This PR moves all the env var logic into the values.yaml instead of the template helper.  
The original intent of the helper was to handle setting env vars that all services shared based on their dependencies.  In reality, there are so exceptions that it became very difficult to modify env vars and to add more exceptions.
I propose explicitly listing out each service's env vars in the values.yaml, utilizing `tpl` to handle situations where services rely on each other. This has the advantage of allowing users to set the env vars for each service exactly how they need. 
Fixes #340
=> [opentelemetry-demo] Move env vars into values.yaml

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/templates/_objects.tpl, charts/opentelemetry-demo/templates/component.yaml, charts/opentelemetry-demo/templates/jaeger.yaml, charts/opentelemetry-demo/values.schema.json, charts/opentelemetry-demo/values.yaml
This PR refactors the chart's image configuration options to be more flexible and apparent.  Users may now:
1. change the jaeger image settings
2. change the default image settings for otel demo services.  this was doable before, but only for repository and pullSecrets.  Now includes tag and pullPolicy.
3. change individual service image settings.  Previously could only set the repository and tag.
Fixes #406
=> [opentelemetry-demo] Refactor image configuration

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/templates/role.yaml, charts/opentelemetry-operator/templates/rolebinding.yaml
Currently leader election role/rb are conditioned by the `role.create` flag . I've made it dependent on the existing `manager.leaderElection.enabled` as well .
=> [operator] Create leader election role/rb only when leaderElection enabled

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/jaeger.yaml, charts/opentelemetry-demo/values.yaml
The docker library postgres has multiarch images which works with ARM64 hosts. Currently the demo works poorly on M1 Macs because a number of images being used are amd64 only, this improves the situation by fixing the Postgres image.
I'm also assuming `cimg/postgres` doesn't have anything special for OTEL specifically. I checked their Dockerfile and it looked pretty vanilla, so I think this change should be minimal.
=> [demo] Use docker library postgres image which has multiarch images

.github/actions/setup/action.yaml
Adds the dependency chart so that `helm dependency build` works as expected.  This hasn't been causing issues because any time `check-examples` was run we had already run `ct lint`, which added the dependency repo.  But for PRs that don't need linting, such as this PR and https://github.com/open-telemetry/opentelemetry-helm-charts/pull/434, we still need something to add the dependency repo.
=> [chore] Add dependency step to setup

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/jaeger.yaml, charts/opentelemetry-demo/examples/default/rendered/opentelemetry-collector/configmap.yaml, charts/opentelemetry-demo/examples/default/rendered/opentelemetry-collector/deployment.yaml, charts/opentelemetry-demo/templates/jaeger.yaml, charts/opentelemetry-demo/values.schema.json, charts/opentelemetry-demo/values.yaml
Updates the Jaeger config to be inline with what is used by the otel demo's docker setup
- Set max traces to 10000, this can also be configured by the user with a values.yaml setting.
- Use OTLP instead of Jaeger protocol
- Removed all unused ports
Because the default OpenTelemetry collector config changed, including the exporter used, a chart minor version bump was in order.
=> [demo] - update jaeger config

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/jaeger.yaml, charts/opentelemetry-demo/examples/default/rendered/opentelemetry-collector/configmap.yaml, charts/opentelemetry-demo/examples/default/rendered/opentelemetry-collector/deployment.yaml, charts/opentelemetry-demo/templates/NOTES.txt, charts/opentelemetry-demo/values.yaml
This adds CORS rules to allow any `http://` or `https://` origin to send OTLP over HTTP data into the collector.
Since the browser/ui when exposed will try to send traces to `http://localhost:4318`. If the user exposes the collector on this port using `kubectl port-forward` and has the proper CORS rules setup they can make it work and see the trace originate from the web browser.
=> [demo] - expose collector to browser spans

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/UPGRADING.md, charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/templates/clusterrole.yaml, charts/opentelemetry-operator/values.yaml
BUMP [opentelemetry-operator to 0.61.0](https://github.com/open-telemetry/opentelemetry-operator/releases/tag/v0.61.0)
There is a documented breaking change related to `Jaeger receiver no longer supports remote sampling`. See release notes
=> [operator] - BUMP opentelemetry-operator to 0.61.0

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/UPGRADING.md, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/templates/NOTES.txt, charts/opentelemetry-operator/values.yaml
Closes: https://github.com/open-telemetry/opentelemetry-helm-charts/issues/446
Not sure how do we approach this breaking change?
I added a notice, is it good enough? Or should we roll-out this by first adding a Notice and then after some time making the change?
Example of it rendered:
```                                                           
helm install opentelemetry-operator --set "admissionWebhooks.certManager.enabled=false" .
NAME: opentelemetry-operator
LAST DEPLOYED: Wed Oct 26 11:24:31 2022
NAMESPACE: sys-mon
STATUS: deployed
REVISION: 1
NOTES:
opentelemetry-operator has been installed. Check its status by running:
kubectl --namespace sys-mon get pods -l "release=opentelemetry-operator"
Visit https://github.com/open-telemetry/opentelemetry-operator for instructions on how to …
```
=> [opentelemetry-operator] change collector image to contrib

README.md
@puckpuck is a maintainer of https://github.com/open-telemetry/opentelemetry-demo and an active contributor to the demo chart.
=> Add Pierre Tessier as an approver

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/jaeger.yaml, charts/opentelemetry-demo/templates/_helpers.tpl, charts/opentelemetry-demo/templates/_pod.tpl, charts/opentelemetry-demo/values.schema.json, charts/opentelemetry-demo/values.yaml
**Description**
Enables https://github.com/open-telemetry/opentelemetry-helm-charts/issues/438 by adding new properties to override environment variables. It supports to overwrite and/or add variables to the default section or to every individual component without the need of repeating the whole env lists.
It indirectly also adds support for templated default envs, so using templates in the env variable of the default section.
It adds only new properties and with that the approach is fully compatible.
The merge logic for the environment variables is implemented in a dedicated helper template which gets applied twice; for generating the default envs and the component specific ones.
The PR does not support to override in the component an environment variable defined in the default section. …
=> [demo] support overriding of env variables

charts/opentelemetry-demo/Chart.lock, charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/jaeger.yaml, charts/opentelemetry-demo/examples/default/rendered/opentelemetry-collector/configmap.yaml, charts/opentelemetry-demo/examples/default/rendered/opentelemetry-collector/deployment.yaml, charts/opentelemetry-demo/examples/default/rendered/opentelemetry-collector/service.yaml, charts/opentelemetry-demo/examples/default/rendered/opentelemetry-collector/serviceaccount.yaml
Bumps demo images to 1.1.0 which fixes issues using the chart locally on Apple Silicon.
Bumps collector dependency to 0.39.1
=> [opentelemetry-demo] Bump demo and collector version

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/jaeger.yaml, charts/opentelemetry-demo/templates/_helpers.tpl, charts/opentelemetry-demo/templates/_pod.tpl
Before this change,  the overall default environment variables are added before the component-level environment variables for each pod. This change reverses that order.
This is trying to solve a situation, where I want to add an additional attribute as part of the `OTEL_RESOURCE_ATTRIBUTES`   variable defined at the overall level. My definition would include a new environment variable that I add to each component, but since those variables are added to the pod template after, they are not picked up using the `$(MY_VAR_NAME)` syntax.  With this change, the following values passed into a helm install will work as expected.
```
default:
envOverrides:
- name: OTEL_RESOURCE_ATTRIBUTES
value: service.name=$(OTEL_SERVICE_NAME),k8s.namespace.name=$(OTEL_K8S_NAMESPACE),k8s.node.name=$(OTEL_K8S_NODE …
```
=> [demo] - change order of default and component env vars

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/jaeger.yaml, charts/opentelemetry-demo/values.yaml
Latest version of `quoteservice` doesn't use `grpc` anymore.
This PR updates the Traces protocol as well as the OTLP endpoint to use the `HTTP` port of the collector.
This was changed in https://github.com/open-telemetry/opentelemetry-demo/pull/546.
And fixed in the `docker-compose` file in https://github.com/open-telemetry/opentelemetry-demo/pull/554.
=> Update trace protocol and endpoint

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/jaeger.yaml, charts/opentelemetry-demo/values.yaml
Fixes #530 
To fix this, I first rendered the k8s manifests for each scenario as follows:
```
helm template my-otel-demo open-telemetry/opentelemetry-demo -n otel-demo -f charts/opentelemetry-demo/values.yaml > otel-demo.yaml
```
and
```
helm template my-otel-demo open-telemetry/opentelemetry-demo -n otel-demo > otel-demo-2.yaml
```
I ran a diff of the 2 files, and noticed that `otel-demo.yaml` was missing the OTLP gRPC endpoint configuration:
```yaml
otlp:
protocols:
grpc:
endpoint: 0.0.0.0:4317
```
After adding this configuration to `values.yaml`, it appeared to fix the issue.
=> Specify grpc endpoint in otlp receiver config

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana/deployment.yaml, charts/opentelemetry-demo/examples/default/rendered/opentelemetry-collector/deployment.yaml, charts/opentelemetry-demo/examples/default/rendered/prometheus/cm.yaml, charts/opentelemetry-demo/values.yaml
The demo 1.2 release had some issues, that needed to get fixed.  This picks up those changes (v1.2.1)
Also cleans up a few small things that were causing pain (exasperated by the issue in the demo 1.2 release).
- Prometheus will now only scrape in its own namespace
- Quote service properly routes OTLP data
- Jaeger routing from frontendproxy is fixed
- Adjusts memory limits for several components
This PR depends on the Demo 1.2.1 release images being created.
=> [demo] - release 1.2.1

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/templates/_objects.tpl
Currently when you set the following default values:
```
affinity:
foo: bar
tolerations:
- baz: qux
```
it renders into `components.yaml`:
```
spec:
affinity:
'{}'
tolerations:
'[]'
```
Moreover setting them directly on a component generates this:
```
affinity:
'foo: bar'
tolerations:
'- baz: qux'
```
This change fixes the apparent issue such that setting these values:
```
default:
schedulingRules:
affinity:
foo: bar
tolerations:
- baz: qux
components:
accountingService:
schedulingRules:
affinity:
foo: quux
tolerations:
- baz: corge
```
generates the appropriate yaml:
```
(accountingService)
affinity:
foo: quux
tolerations:
- baz: corge
(others)
affinity:
foo: bar
tolerations:
- baz: qux
```
P.S. This is my first PR here, so apologies if I've done something the wrong way!
=> [opentelemetry-demo] Fix tolerations and affinity templating.

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/templates/_objects.tpl, charts/opentelemetry-demo/values.schema.json, charts/opentelemetry-demo/values.yaml
Given the large number of components in the demo, the values file was expanding unnecessarily for unused parameters.  
This PR removes all unused (default) parameters from each demo component. Only parameters that override defaults are included. At the top of the `components` section is a commented sample for a component with all available parameters specified and documented.
This change reduces the number of lines in the values.yaml files by 16% (635 vs 759)
=> [demo] simplify default values

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/templates/_objects.tpl
The problem we're fixing here is the following: after change https://github.com/open-telemetry/opentelemetry-helm-charts/pull/557, the `{{- if .schedulingRules }}` check yields "false" by default, which means that configuring scheduling rules via `default` map in chart values (i.e., having non-empty `default.schedulingRules`) is no longer working (all [logic here](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-demo/templates/_objects.tpl#L30-L41) is simply ignored).
This PR removes the `{{- if .schedulingRules }}` check, but also introduces a temporary variable `$schedulingRules` that is always meant to be non-null.
=> [opentelemetry-demo] Fix schedulingRules handling for demo components

charts/opentelemetry-operator/CONTRIBUTING.md, charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook-with-cert-manager.yaml
=> Fix minstrumentation.kb.io webhook with certmanager

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook.yaml
Problem I need to solve:
Change the kubernetes opentelemetry webhook name so that it is called before other webhooks, as kubernetes calls the webhooks in alphabetical order.
Issue:
- When using nameOverride, to set the operator name to, say "aa-opentelemetry-operator";
- When setting certManager.enabled to false (in my org, we don't use a cert-manager);
- When applying applying a `kind: Instrumentation` ```kubectl apply -f instr.yaml ```
I get this error:
```
Error from server (InternalError): error when creating "instr.yaml": Internal error occurred: failed calling webhook "minstrumentation.kb.io": failed to call webhook: Post "https://aa-opentelemetry-operator-webhook-service.tracing.svc:443/mutate-opentelemetry-io-v1alpha1-instrumentation?timeout=10s": x509: certificate is valid for …
```
=> [operator] Update operator-webhook.yaml

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/templates/_objects.tpl, charts/opentelemetry-demo/values.schema.json, charts/opentelemetry-demo/values.yaml
This allows components to be configured so that they can be recreated if an endpoint fails to return a success code.
Specifically, this is configured for the featureflagService in order to resolve:
https://github.com/open-telemetry/opentelemetry-demo/issues/695
When the ffspostgres pod gets recreated (for any reason) the database is deleted and migrations (tables) are lost. This causes the featureflag index endpoint to error. The liveness probe recreates the featureflag pod, which runs its migrations, restoring a working state.
=> [opentelemetry-demo] Adds liveness probe option to demo components

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/values.yaml
I was hitting the same issues as #596 - and based on my observations of the process under light load the RSS is in the range of 78-84 MB, but even at cold startup it's above the 70MB limit.
I propose increasing to 100Mi so there's a bit of safety margin here. 
Signed-off-by: Irving Popovetsky <irving@honeycomb.io>
=> Increase memory allocation to paymentservice to prevent OOMKills

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/values.yaml
Fixes: #624 and Closes #623
The PR will abstract the name of the OpenTelemetry Collector away from the components into a higher-level default environment variable `OTEL_COLLECTOR_NAME` pushed into all components. The components will then leverage this variable with Kubernetes environment variable expansion as needed using the `$(OTEL_COLLECTOR_NAME)` syntax.
With this change users can now deploy the collector in daemonset mode, and only change 1 environment variable override to have it working. This also opens up possibilities for uers that have the OpenTelemetry collector installed outside of the demo.
Tested and works with the following specified in a values file
```
default:
envOverrides:
- name: OTEL_COLLECTOR_NAME
value: $(OTEL_K8S_NODE_NAME)
opentelemetry-collector:
mode: daemonset …
```
=> [demo] abstract collector name from demo components

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/README.md, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana/role.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana/role.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/values.yaml
The demo currently gives a warning about PodSecurityPolicy being deprecated in K8s 1.25+
```W0301 21:24:42.684567   27040 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0301 21:24:43.766445   27040 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0301 21:24:43.807527   27040 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
```
This change disables the Grafana subchart from using PodSecurityPolicy, and allows the chart to be installed without warnings.  Grafana continues to function as expected.
=> [demo] - disable PodSecurityPolicy use

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/prometheus/deploy.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/prometheus/deploy.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/values.yaml
After doing a long-running test (4 weeks), Prometheus never exceeded 250Mi in memory usage. This sets the limit to a more conservative number and minimizes cluster requirements to run the demo
=> [demo] lower prometheus memory limit

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/_helpers.tpl, charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook.yaml, charts/opentelemetry-operator/values.schema.json, charts/opentelemetry-operator/values.yaml
Hi there.
Mutating webhooks are called sequentially in alphabetical order, whereas validating webhooks are called independently in parallel.
In some cases MutatingWebhooks should run in specific order. For example, when using Opentelemetry Operator and [Gatekeeper Mutations](https://open-policy-agent.github.io/gatekeeper/website/docs/mutation), I want to modify securityContext for auto-instrumentation initContainer.
But, because of ordered sequential calling of mutating webhooks, gatekeeper mutation is called first, and does nothing, because auto-instrumentation initContainer is not created yet.
This MR implements optional ordering prefix for MutatingWebhookConfiguration. By default, prefix value is empty, and webhook name doesn't change during upgrade from previous chart versions. When …
=> [operator] add a prefix for ordering MutatingWebhookConfiguration

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/values.schema.json, charts/opentelemetry-operator/values.yaml
Bump the kube-rbac-proxy to v0.14.0 that fixes some CVEs as noted in these [release notes](https://github.com/brancz/kube-rbac-proxy/releases)
=> Bump kube-rbac-proxy v0.14.0

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/values.yaml
Fixes: #666 
Continues on the work done in PR #685 and adds similar initContainers for the three services that depend on Kafka.
For consistency's sake, the Postgres check on the featureflagservice was also updated.
=> [demo] add kafka init checks

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/values.yaml
Fixes #691 
When we moved to abstract the collector name away in #629, we broke OTLP export for Kafka because it didn't include the default env vars. This fixes that.
=> [demo] add default env to kafka

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/values.yaml
Though it is rare, the `cartservice` component can startup before `redis` is ready, causing a failure and restart. This keeps that pod from starting until redis is ready.
=> [demo] add redis health check

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/values.yaml
Updates the environment variables for all components to align with [this PR](https://github.com/open-telemetry/opentelemetry-demo/pull/809) from the Demo repo.
Added a new default level environment variable for `OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE` since this will be consistent for all components as they adopt metrics.
Re-ordered how some variables are listed to align with how the Demo repo has them set up. Generally speaking, they will be in this order:
- Port for the component to bind to
- addresses for downstream components
- other specific component vars
- OTEL vars
=> [demo] update env variables

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/UPGRADING.md, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/templates/_helpers.tpl, charts/opentelemetry-demo/templates/_objects.tpl
fix https://github.com/open-telemetry/opentelemetry-helm-charts/issues/714
1. service port.name to align istio naming standard
2. adjust pod app.kubernetes.io/name to make istio happy
=> [demo]:  label and port.name align istio standard

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/certmanager.yaml, charts/opentelemetry-operator/values.schema.json, charts/opentelemetry-operator/values.yaml
Description:
My company has a use case where adding annotations to the cert and issuer created by the cert-manager would be very useful. This shouldn't affect previous behavior. Let me know if I missed anything.
Testing:
Tested manually against a Kubernetes 1.26 cluster.
=> Add support for adding annotations to the cert-manager cert and issuer objects

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook.yaml, charts/opentelemetry-operator/values.yaml
Following the change done in https://github.com/open-telemetry/opentelemetry-helm-charts/pull/760, we also need to be able to add custom labels to the [secret](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook.yaml#L6) that is created. This PR adds that possibility.
=> [operator] Allow setting custom secret labels

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/deployment.yaml, charts/opentelemetry-operator/values.yaml
This PR adds the missing container level securityContext to the deployment. 
This option is required to run the operator inside a restricted namespace
=> feat: add container specific securityContext

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/servicemonitor.yaml
Currently if you do not specify a ServiceMonitor annotation it outputs null.
This is an issue if you use Argo CD with self-healing enabled. This is because Kubernetes strips this property when it is applied, leading to Argo CD to notice a difference in this property, causing it to re-apply which obviously does nothing (meaning it gets stuck in a loop).
=> [operator] Make ServiceMonitor annotation optional

.github/workflows/operator-test.yaml, charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/crds/crd-opentelemetryinstrumentation.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/deployment.yaml, charts/opentelemetry-operator/values.schema.json, charts/opentelemetry-operator/values.yaml
Operator 0.77.0 added support for Go auto-instrumentation.  As a result, this PR adds:
- the ability to set the go image repo and tag.
- the ability to set feature-gates flag.
=> [operator] Bump operator to 0.77.0

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/README.md, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
The example in the README for a collector configured as a daemonset omitted the `hostNetwork: true` which is required for an application-side Open Telemetry SDK to communicate with the collector on the node.
=> mode: daemonset example indicates hostNetwork: true is required

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/prometheusrule.yaml
The chart deploys alerting rules `ReconcileErrors` and `WorkqueueDepth` to monitor the operator. However, since these rules do not filter on any labels they apply to any operator deployed in the Kubernetes cluster.
To contain this chart only to the Opentelemetry Operator this PRs adds the relevant labels to the PrometheusRules.
No user impact is expected with this change
=> [operator] limit prometheus rules to opentelemetrycollector application

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/opentelemetry-collector/configmap-agent.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/opentelemetry-collector/daemonset.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/prometheus/deploy.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/opentelemetry-collector/configmap.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/opentelemetry-collector/deployment.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/prometheus/deploy.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/opentelemetry-collector/configmap.yaml, charts/opentelemetry-demo/examples/default/rendered/opentelemetry-collector/deployment.yaml, charts/opentelemetry-demo/examples/default/rendered/prometheus/deploy.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/opentelemetry-collector/configmap.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/opentelemetry-collector/deployment.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/prometheus/deploy.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/values.yaml
Updates Prometheus to use OTLP write. Collector exporter updated accordingly.
References this [demo repo PR](https://github.com/open-telemetry/opentelemetry-demo/pull/1149)
=> (demo): update prometheus to use otlp write

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/opentelemetry-collector/configmap-agent.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/opentelemetry-collector/daemonset.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/opentelemetry-collector/configmap.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/opentelemetry-collector/deployment.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/opentelemetry-collector/configmap.yaml, charts/opentelemetry-demo/examples/default/rendered/opentelemetry-collector/deployment.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/opentelemetry-collector/configmap.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/opentelemetry-collector/deployment.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/values.yaml
Adds the `http://` scheme to the Prometheus endpoint. I'm not sure how this worked or was missed before. Grafana charts now work properly in the demo.
=> (demo): fix prometheus endpoint

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/values.yaml
This is a tiny glitch - but do we even need this to ensure logs are collected and exporter?
Could be merged just after #925
=> [otel-demo] Fix exporter environment variable

.github/actions/setup/action.yaml, .github/workflows/operator-test.yaml, Makefile, charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/crds/crd-opentelemetry.io_opampbridges.yaml, charts/opentelemetry-operator/crds/crd-opentelemetryinstrumentation.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/clusterrole.yaml, charts/opentelemetry-operator/templates/deployment.yaml, charts/opentelemetry-operator/values.schema.json, charts/opentelemetry-operator/values.yaml
With the merging of the [operator release](https://github.com/open-telemetry/opentelemetry-operator/pull/2297#pullrequestreview-1708409527), the opamp-bridge has now been released. This PR upgrades the helm chart to the latest version and includes the bridge CRD.
Also had to update testing action. see [here](https://github.com/helm/chart-testing-action/issues/132)
=> upgrade to 0.88 include bridge

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/README.md, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/templates/_objects.tpl, charts/opentelemetry-demo/values.schema.json, charts/opentelemetry-demo/values.yaml
Adds support to specify the number of replicas for all components or specifically for individual ones. Allowing to set replicas and various load generator settings allows the demo to be deployed in more complex performance-affected scenarios where observability tooling can be used to diagnose the root cause.
Shared demo components such as Redis, Postgres, and Kafka have a `replicas: 1` setting specified at the component level. All other components do not set/override this value, which will inherit from default (1).
=> [demo] add replicas support

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook.yaml
This PR explicitly defines the rule scope for the admission-webhook configurations.
Since the rules are only defining one resource type per rule, I chose to explicitly define the scope instead of providing variables that would allow customization.
This fixes #939 
Thanks in advance!
=> Adding namespace scope to webhook config

.github/workflows/operator-test.yaml, charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/crds/crd-opentelemetry.io_opampbridges.yaml, charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/values.yaml
Recent changes to operator E2E tests require them to be run from the operator repository root. However, the Chart kuttle config file also assumes tests are run from the chart repository root, so I needed to manually specify the CRD dir in the CI.
=> Bump operator to 0.90.0

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook.yaml
Although we can set the port on the service, we need to change the validating and mutating webhook configuration as well. cc @TylerHelmuth
=> Set Port for the webhook

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/_helpers.tpl
Reproduction step:
1. helm install with `autoGenerateCert`
```bash
helm install my-opentelemetry-operator charts/opentelemetry-operator --set admissionWebhooks.certManager.enabled=false --set admissionWebhooks.autoGenerateCert.recreate=false -n insight-system
```
2.  uninstall the released chart:
```bash
helm uninstall my-opentelemetry-operator
```
3. re-install with `autoGenerateCert`
```bash
helm install my-opentelemetry-operator charts/opentelemetry-operator --set admissionWebhooks.certManager.enabled=false --set admissionWebhooks.autoGenerateCert.recreate=false -n insight-system
```
Error occurs：
```bash
`opentelemetry-operator/templates/_helpers.tpl:100:18: executing "opentelemetry-operator.WebhookCert" at <first $prevHook.webhooks>: error calling first: runtime error: invalid memory …
```
=> [opentelemetry-operator] fix `opentelemetry-operator.WebhookCert` nil pointer

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/README.md, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
Create flag is only used in doc (https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-helm-charts+%22certManager.create%22&type=code), but enabled seems be the correct name for the flag (https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-helm-charts%20%22certManager.enabled%22&type=code)
=> fix(doc): flag name used to enable certManager

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/templates/_pod.tpl, charts/opentelemetry-demo/values.yaml
Allows users to completely override the `OTEL_RESOURCE_ATTRIBUTES` environment variable at the component level or append to it using a special `OTEL_RESOURCE_ATTRIBUTES_EXTRA` environment variable.
Users can now specify:
```
components:
frontendProxy:
envOverrides:
- name: OTEL_RESOURCE_ATTRIBUTES_EXTRA
value: "net.component=proxy"
```
And the resource attributes for the frontendProxy will also contain a `net.component=proxy` attrbribute.
=> [demo] append to otel resource attributes

.github/workflows/operator-test.yaml, charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/clusterrole.yaml, charts/opentelemetry-operator/values.yaml
Part of https://github.com/open-telemetry/opentelemetry-operator/issues/2656
I had to add new permissions to the operator ClusterRole due to https://github.com/open-telemetry/opentelemetry-operator/pull/2575. I ended up copying the rules from the operator's kustomize manifest, resulting in a smaller ClusterRole at the end of it.
=> Bump operator to 0.95.0

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/UPGRADING.md, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/values.schema.json
This can catch misspellings like the one below, which I encountered when
using this Helm chart myself (but the previous validation did not catch it):
Error: values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-operator:
- (root): Additional property kubeRBACPRoxy is not allowed
I was not entirely sure about the version, so I bumped the minor version
as this change may reject charts that worked previously (if they contain
unknown or unspecified fields).
The three other charts already use `additionalProperties: false` in many
places, this adds similar validation to the `opentelemetry-operator` chart
as well: https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-helm-charts+additionalProperties&type=code
=> [operator] Reject invalid/unknown properties using `additionalProperties`

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/values.schema.json, charts/opentelemetry-operator/values.yaml
This fixes #1095 
I also added the property to the `values.yaml` to make it more clear that this is available.
```bash
$ helm template my-otel-operator . --set fullnameOverride="fullnameoverride-otel-operator" -s templates/deployment.yaml| yq '.metadata.name'
fullnameoverride-otel-operator
```
=> [opentelemetry-operator] fix `fullnameOverride`

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/values.schema.json
This will allow to add extra `WATCH_NAMESPACE` env var to the manager, since it is a known env var https://github.com/open-telemetry/opentelemetry-operator/blob/main/main.go#L225C41-L225C56
=> Allow `WATCH_NAMESPACE` as `manager.env`

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/values.schema.json, charts/opentelemetry-operator/values.yaml
While updating the opentelemetry-operator helm chart from 0.49.1 -> 0.52.2 we get an error during `helm template`:
```bash
Error: values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-operator:
- securityContext: Additional property seccompProfile is not allowed
```
Our security context is defined like that:
```yaml
securityContext:
runAsGroup: 65532
runAsNonRoot: true
runAsUser: 65532
fsGroup: 65532
seccompProfile:
type: RuntimeDefault
```
Everything worked up until now. I think the 'issue' was introduced with https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1065.
The securitycontext in the `charts/opentelemetry-operator/values.schema.json` file is different.
After this PR it is the same for all occurences.
An alternative would be …
=> Consistent definition of securityContext schema values

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/clusterrole.yaml, charts/opentelemetry-operator/templates/deployment.yaml, charts/opentelemetry-operator/values.schema.json, charts/opentelemetry-operator/values.yaml
The `--create-rbac-permissions` argument on the manager requires extra RBAC permissions to actually use. The helm chart should add a flag to make enabling it easy.
=> feat: Add option to enable --create-rbac-permission on operator

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
I would normally wait until https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1119 gets merged, but this version of the operator completely breaks for me. I need this ASAP so I figured I'd make the clean ups that are needed on the other PR.
=> chore: Bump operator version to v0.97.1

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/UPGRADING.md, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/_helpers.tpl, charts/opentelemetry-operator/values.schema.json, charts/opentelemetry-operator/values.yaml
[Issue Link](https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1120)
The operator chart has been updated to read contents of the file path provided in below variables.
```
cert_file: ""
key_file: ""
ca_file: ""
```
Screenshot to verify that the contents are read and added to secret correctly.
=> [opentelemetry-operator] read cert contents

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/clusterrole.yaml
Fixes [opentelemetry-operator/issues/2824](https://github.com/open-telemetry/opentelemetry-operator/issues/2824).
Since introduction of `--create-rbac-permissions` Operator is required to have permissions it tries to grant ro Collectors. Example [code](https://github.com/open-telemetry/opentelemetry-operator/blob/c65629b3b9fcb722e770eb58b73ea4f5cc8bc63f/internal/manifests/collector/parser/processor/processor_k8sattributes.go#L78-L102).
This PR adds `extensions/replicasets` permissions unconditionally to mirror `apps/replicasets` and `nodes + namespaces` permissions only when `--create-rbac-permissions` is enabled.
=> Add permissions to operator's ClusterRole that it tries to grant to some collectors

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/flagd/demo.flagd.json
Add adServiceHighCpu featureflag to flagd file. See upstream PR here: https://github.com/open-telemetry/opentelemetry-demo/pull/1510
=> adservice add adServiceHighCpu featureflag to flagd files

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/README.md, charts/opentelemetry-operator/UPGRADING.md, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/_helpers.tpl, charts/opentelemetry-operator/values.schema.json
Fixes issue #1142 
Update references to removed variables when providing user managed certificates for the operator webhook.
Tested locally by generating the templates
=> [opentelemetry-operator] fix references to old variables

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/values.schema.json, charts/opentelemetry-operator/values.yaml
We should be able to set the name of the service account used. If no service account name is set it defaults to `opentelemetry-operator`.
This also helps with confusion when seeing the values that are in `values.yaml`, specifically this part:
```yaml
serviceAccount:
create: true
annotations: {}
```
Using existing schema uncommenting `# name:` will break the chart
Resolves #1144
=> [Operator] Allow setting of manager service account name, default value if not used

.github/workflows/operator-test.yaml, charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/README.md, charts/opentelemetry-operator/UPGRADING.md, charts/opentelemetry-operator/ci/cert-manager-disable-nameoverride-values.yaml, charts/opentelemetry-operator/ci/cert-manager-disable-values.yaml, charts/opentelemetry-operator/ci/nameoverride-values.yaml, charts/opentelemetry-operator/ci/secret-name-nameoverride-values.yaml, charts/opentelemetry-operator/ci/secret-name-values.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/default/values.yaml, charts/opentelemetry-operator/templates/NOTES.txt, charts/opentelemetry-operator/values.yaml
Works towards https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1153
This PR removes the default `manager.collectorImage.repository` from the operator chart so that installs/upgrades fail for users depending on the previously set `contrib` image.
Adds a new section to UPGRADING.md to guide users through this failure.
=> [operator] Require collector image be set

.github/CODEOWNERS, README.md
@jaronoff97 has been a big help with all the helm chart, reviewing PRs and contributing improvements. I specifically want to call out this work on the the long-standing issue of installing the operator and CRs at the same time - the new opentelemetry-kube-stack chart will level-up our new user experience in Kubernetes.
=> Promote jaronoff97 to Approver

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/flagd/demo.flagd.json, charts/opentelemetry-demo/values.yaml
flagd.json and frontend/frontend proxy env var changes to include flagd
increased frontend pod ram limit
connected PRs:
https://github.com/open-telemetry/opentelemetry-demo/pull/1515
https://github.com/open-telemetry/opentelemetry-demo/pull/1571
=> [demo] Slowloading of images

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/README.md, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/deployment.yaml, charts/opentelemetry-operator/values.yaml
Ensure SERVICE_ACCOUNT_NAME env variable is set in pods to align with the deprecation of the `create-rbac-permission flag`
Addressing functionality issues with k8sattributes.
Closes: #1224
=> [operator] Align to `create-rbac-permission` flag deprecation

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/prometheusrule.yaml, charts/opentelemetry-operator/values.schema.json, charts/opentelemetry-operator/values.yaml
This is needed for routing alerts to 3rd party systems via labels and using custom annotations for alertmanager templates.
=> [operator] Add extra labels/annotations on default alerts

Makefile
This will make it easier to understand why the lint command failed without a reviewer needing to fork it locally.
I tested with just manually editing something in the rendered and it found it very quickly:
```
find: ./tmp/default/opentelemetry-operator/charts: No such file or directory
diff -r charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml ./tmp/default/opentelemetry-operator/templates/clusterrolebinding.yaml
7c7
<     helm.sh/chart: opentelemetry-operator-0.64.2
---
>     helm.sh/chart: opentelemetry-operator-0.64.1
12c12
<
---
>
34c34
<
---
>
Failed default. run 'make generate-examples' to re-render the example with the latest default/values.yaml
make: *** [check-examples] Error 1
```
=> Show the diff in CI

Makefile, charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/conf/crds/crd-opentelemetrycollector.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
closes #1259 
This matches the port for the conversion webhook with the port for webhook service
=> Set port for webhook in conversion webhook

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/servicemonitor.yaml
Fixes indentation issues causing an invalid ServiceMonitor spec when using relabeling/metricRelabeling configs  https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1287
=> [operator] fix: move 'relabelings' and 'metricRelabelings' configs under endpoints in serviceMonitor spec

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/values.schema.json
It's currently impossible to deploy the operator chart without requests and/or limits. CPU limits are of particular concern; they are essentially considered harmful at this point.
Additionally, the schema is incomplete by not allowing for [(as seen on this page)](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container):
1. `spec.containers[].resources.requests.hugepages-<size>`
2. `spec.containers[].resources.limits.hugepages-<size>`
So I also set `additionalProperties` to true for the respective limits/requests to support arbitrary hugepage sizes.
This PR allows the user to freely enable, disable or set any value in limits or requests to whatever they want including, most importantly, removing them entirely:
```yaml …
```
=> Remove required container resources

README.md
Looks like the name wasn't moved from approver to maintainer but rather added and is now in two places 😅
=> docs: one too many jacobs

charts/opentelemetry-kube-stack/Chart.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml, charts/opentelemetry-kube-stack/templates/collector.yaml, charts/opentelemetry-kube-stack/values.yaml
Remove setting the image version from the collector as that is handled by the operator's functionality. Also fixes the bridge's image which was hardcoded.
=> Remove image setting when not needed

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/templates/_objects.tpl, charts/opentelemetry-demo/values.schema.json, charts/opentelemetry-demo/values.yaml
This adds a new option to the demo chart, allowing to set the revisionHistoryLimit for the Deployments. This parameter already exists in the collector helm chart (if mode=deployment), and it is useful for the demo deployments as well.
=> [demo] add revisionHistoryLimit parameter

charts/opentelemetry-kube-stack/Chart.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml, charts/opentelemetry-kube-stack/templates/_helpers.tpl
The labels in some `ServiceMonitor` selectors doesn't match the ones in the `Service` objects, specifically the label `release` is missing from some of them.
This PR attempts to solve the problem described above. I realized the `opentelemetry-kube-stack.labels` variable used to populate the labels in most `Service` objects was missing the `release` label. So the fix is as easy to add this label to this variable.
Thanks!
Fixes #1362
=> [opentelemetry-kube-stack]: Fix missing "release" label to opentelemetry-kube-stack.labels

charts/opentelemetry-kube-stack/Chart.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml, charts/opentelemetry-kube-stack/values.schema.json
This is to fix the following error and details are documented in this [issue](https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1360)
```
\Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-kube-stack:
- kubeScheduler.service: Additional property selector is not allowed
```
=> [opentelemetry-kube-stack]: Fix "Additional property selector is not allowed" error while adding selector label to service

charts/opentelemetry-kube-stack/Chart.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml, charts/opentelemetry-kube-stack/values.schema.json
This is to enable the option to add labels to the components such as servicemonitor.
While using a separate collector for the controlplane metrics, we need to add a label to serviceMonitors that we are planning to lookup separately (Later TA can us this label to filter the serviceMonitor lookup). This PR is specifically to fix the following error that we get while adding the label to serviceMonitor components.
```
- kubeEtcd.serviceMonitor.additionalLabels: Additional property component is not allowed
- kubeApiServer.serviceMonitor.additionalLabels: Additional property component is not allowed
- kubeControllerManager.serviceMonitor.additionalLabels: Additional property component is not allowed
- kubeScheduler.serviceMonitor.additionalLabels: Additional property component is not allowed …
```
=> [opentelemetry-kube-stack] Adding additional labels

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/deployment.yaml, charts/opentelemetry-operator/values.yaml
To close #1344 as the earlier PR #1345 didn't go through. Increasing the version to `0.18.1` which is the latest and fixes CVE-2024-28180 and GHSA-xr7q-jx4m-x55m as per their [release](https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.18.1) on top of those fixed in the original proposed version of `0.18.0`.
=> [opentelemetry-operator] Update kube-rbac-proxy image to 0.18.1 to remediate vulnerabilities

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/NOTES.txt
previous：
```bash
kubectl --namespace {{ .Release.Namespace }} get pods -l "release={{ $.Release.Name }}"
```
now:
```bash
kubectl --namespace {{ .Release.Namespace }} get pods -l "app.kubernetes.io/name={{ $.Release.Name }}"
```
this will correctly list pods like blew：
```bash
$ kubectl --namespace opentelemetry-operator-system get pods -l "app.kubernetes.io/name=opentelemetry-operator"
NAME                                     READY   STATUS    RESTARTS   AGE
opentelemetry-operator-556cf4f79-8bqwd   2/2     Running   0          8m47s
```
=> docs: docs: adjust a description error in NOTES.txt file

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/_helpers.tpl, charts/opentelemetry-operator/templates/deployment.yaml
The operator does not like feature gates being quoted.
Feature gates are also a flag based on presence. If the flag is present, it is understood to be true, absence leaves the default value.
=> fix: Configure feature gates appropriately

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/prometheusrule.yaml, charts/opentelemetry-operator/values.schema.json, charts/opentelemetry-operator/values.yaml
Adding the `manager.prometheusRule.defaulRules.duration` value to allow change of the default `5m` default alerts duration.
=> [operator] Allow PrometheusRule duration set

charts/opentelemetry-kube-stack/Chart.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/values.yaml, charts/opentelemetry-kube-stack/templates/_helpers.tpl, charts/opentelemetry-kube-stack/templates/collector.yaml
Please refer the following issue to get more details on this PR, 
closes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1426
=> Fix collector label addition issue

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/values.yaml
OTEL_SERVICE_NAME envvar is set on all components as one of envvars listed in default.env, to the value of app.kubernetes.io/component label. Recently 51993de76504 ("Bump dependencies and fix grafana dashboards") duplicated OTEL_SERVICE_NAME on the frontendproxy deployment by setting it explicitly to frontend-proxy. A duplicated envvar causes an error when upgrading the opentelemetry-demo chart:
Deployment.apps "opentelemetry-demo-frontendproxy" is invalid:
spec.template.spec.containers[0].env[0].valueFrom: Invalid value: "": may
not be specified when `value` is not empty
My understanding is that the duplicated envvar was introduced in #1422 as a follow-up to open-telemetry/opentelemetry-demo#1768 that introduced it in docker-compose setup of opentelemetry-demo? But I don't have context …
=> [demo] Remove duplicate envvar on frontendproxy

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/values.yaml
Since https://github.com/open-telemetry/opentelemetry-demo/pull/1538 `accountingservice` was rewritten in .NET to showcase the auto-instrumentation.
The OTLP endpoint changed from `grpc` to `http`, but the helm chart never got this change.
This PR fixes it.
=> [demo] fix accountingservice otlp endpoint

charts/opentelemetry-demo/Chart.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/prometheus/deploy.yaml, charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/prometheus/deploy.yaml, charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/default/rendered/component.yaml, charts/opentelemetry-demo/examples/default/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/default/rendered/prometheus/deploy.yaml, charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/prometheus/deploy.yaml, charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/flagd-config.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/prometheus/deploy.yaml, charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml, charts/opentelemetry-demo/values.yaml
Updates Prometheus config for OTLP based on this [guide](https://prometheus.io/docs/guides/opentelemetry/) provided in Prometheus docs.
Also fixes this [issue](https://github.com/open-telemetry/opentelemetry-demo/issues/1816) in the demo repo.
=> [demo] update prometheus otlp config

charts/opentelemetry-kube-stack/Chart.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/clusterrole.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/clusterrole.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml, charts/opentelemetry-kube-stack/templates/clusterrole.yaml
fixes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1444
=> fix[opentelemetry-kube-stack] add persistentvolumeclaims to ClusterRole

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/conf/crds/crd-opentelemetrycollector.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/values.yaml
We're behind on operator releases. 0.116.0 is out, and the helm chart is still at 0.114.1. Updating to 0.115.0 first, will follow up with 0.116.0.
=> Release operator 0.115.0

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/deployment.yaml, charts/opentelemetry-operator/values.schema.json, charts/opentelemetry-operator/values.yaml
This PR is adding the possibility to specify extra environment variable definitions that are not simple name/value pairs, for example when `valueFrom` should be used.
=> feat(opentelemetry-operator): Adding extraEnv

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/_helpers.tpl
To test:
```sh
helm template my-release charts/opentelemetry-operator/ \
--set manager.collectorImage.repository=otel/opentelemetry-collector-contrib \
--set manager.image.tag=v0.116.0@sha256:11edfad24ead5f48140eb12aea642a2716ca0cd9e63eae3851f39c4477f3c2c2 \
| grep app.kubernetes.io/version
```
Bug introduced by https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1461.
See https://github.com/grafana/loki/pull/8260 for a similar fix.
=> fix(opentelemetry-operator): ensure valid version label

charts/opentelemetry-kube-stack/Chart.yaml, charts/opentelemetry-kube-stack/README.md, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml
Added a short note indicating that the `scrape_configs_file` parameter can only be used when running the `opentelemetry-kube-stack` chart locally.
=> [docs] Add note for scrape_configs_file to opentelemetry-kube-stack README

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/UPGRADING.md, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/NOTES.txt, charts/opentelemetry-operator/values.yaml
Having default values makes it impossible to remove the CPU limits since the default values will always be merged in with anything set by the user. Setting CPU limits are considered an anti pattern ref. https://komodor.com/learn/kubernetes-cpu-limits-throttling/
=> fix(opentelemetry-operator): remove default resource values

charts/opentelemetry-kube-stack/Chart.yaml, charts/opentelemetry-kube-stack/charts/crds/crds/monitoring.coreos.com_probes.yaml, charts/opentelemetry-kube-stack/charts/crds/crds/monitoring.coreos.com_scrapeconfigs.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml, charts/opentelemetry-kube-stack/values.schema.json, charts/opentelemetry-kube-stack/values.yaml
Also adds the scrapeconfigs and probes crds from prometheus-operator 0.74.0.
Now that opentelemetry-operator has been bumped, it should be possible to use the scrapeConfigSelector and probeSelector features of the targetallocator in this chart.
=> [kube-stack] Add scrapeconfig and probe selectors to targetAllocator prometheusCR schema

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook.yaml
Related Issue: https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1529
Description:
- Issue: The operator validation webhook can incorrectly use a cert-manager-generated certificate (if a cert-manager exists within the cluster) even when a Helm-generated or user-supplied certificate is specified (`admissionWebhooks.certManager.enabled=false`). This was likely a slight oversight that just has not been caught yet.
- Impact: cert-manager overriding the intended certificates to be used or causing Helm install/upgrade failures for the operator.
- Fix: Ensures that the validation webhook respects the designated certificate source by not including the cert-manager annotation inappropriately, the same way the [mutating webhook …
=> [operator] Fix bug in the operator validation webhook using the wrong certificate

charts/opentelemetry-kube-stack/Chart.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml, charts/opentelemetry-kube-stack/values.yaml
Is there any reasoning on having different resource limits for the cluster and daemonset pods? In my tests I normally see much CPU and memory usage on the daemonset ones:
```
$ k top pod -n opentelemetry-operator-system
NAME                                                              CPU(cores)   MEMORY(bytes)
opentelemetry-kube-stack-cluster-stats-collector-654ccc595wlqtl   2m           27Mi
opentelemetry-kube-stack-daemon-collector-72rcq                   21m          34Mi
opentelemetry-kube-stack-daemon-collector-dlsn2                   29m          34Mi
opentelemetry-kube-stack-daemon-collector-wgcdl                   19m          34Mi
opentelemetry-kube-stack-daemon-collector-xhtgd                   25m          34Mi
opentelemetry-kube-stack-opentelemetry-operator-6695b8446c98xxz …
```
=> [kube-stack]: align cluster and daemon resource limits

charts/opentelemetry-operator/CONTRIBUTING.md, charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml
Describe how to update the operator chart on Mac OS X which comes with a different sed flavour. Also fix list numbering.
Split from https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1566
=> Document sed workaround on Mac OS X

charts/opentelemetry-operator/CONTRIBUTING.md, charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/values.yaml
Make sure people get the latest operator version. The [operator changelog](https://github.com/open-telemetry/opentelemetry-operator/blob/main/CHANGELOG.md#01200) claims that there are no changes for this version, so just bumping should work fine without adjustments.
I also updated the contribution guide with a work around for `sed` problems on Mac OS X.
=> [operator] Bump version to 0.120.0

charts/opentelemetry-kube-stack/Chart.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml, charts/opentelemetry-kube-stack/values.schema.json
Description:
Reformatting values.schema.json to standardize indentation and formatting with pre-commit pretty-format-json hook automation. There were no mismatching indentation in this file like there are in other charts, only list entries were split out to use multiple lines. No json values were added, modified, or removed.
Related PRs: 
- Helps unblock https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1573.
=> [kube-stack] Reformat values.schema.json 

charts/opentelemetry-kube-stack/Chart.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml, charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml, charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml, charts/opentelemetry-kube-stack/templates/hooks.yaml, charts/opentelemetry-kube-stack/values.yaml
This PR introduces the ability to specify an existing service account for the cleanup job. This enhancement allows users to use a pre-existing service account instead of creating a new one, providing more flexibility and control over the service account used for cleanup operations.
Changes:
1. hooks.yaml:
- Added conditional logic to check if existingServiceAccount is specified and not empty.
- If existingServiceAccount is provided, it will be used for the RoleBinding and Job resources.
- If existingServiceAccount is not provided, the default delete-resources-sa service account will be created and used.
3. values.yaml:
- Added a new field existingServiceAccount under cleanupJob to allow users to specify an existing service account.
=> feat(opentelemetry-kube-stack): Added option for user to provide existingServiceAccount for cleanup job

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/README.md, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/values.yaml
- Fix bug where the operator can be scheduled on windows nodes and cause pull image errors. The operator docker image doesn't support windows nodes.
- Tested locally via Minikube by deploying the operator to a Linux node.
- https://github.com/open-telemetry/opentelemetry-operator/issues/642
=> [operator] Fix bug where the operator can be scheduled on windows nodes

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/deployment.yaml, charts/opentelemetry-operator/values.schema.json, charts/opentelemetry-operator/values.yaml
The PR adds configuration option for `revisionHistoryLimit` to control the number of old ReplicaSets for rollback.
There will be no changes in default behaviour.
=> fix(opentelemetry-operator): add revisionHistoryLimit option

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/values.yaml
As per https://github.com/open-telemetry/opentelemetry-helm-charts/blob/0bdda7e6b65507833bdd71555c975f7e4706fd34/charts/opentelemetry-operator/UPGRADING.md, the property is no longer supported here, removed in commit f9707d3aa2ce2debea19c93e5f949deb7cc80ceb
=> Remove 'operator.observability.prometheus' from Helm chart comments

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/README.md, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/default/values.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/values.yaml
Update documentation examples to use the correct collector image repository.
This change follows the context of [Issue #1664](https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1664), which highlights that the current default collectorImage.repository used in Helm install examples (otel/opentelemetry-collector-k8s) no longer provides updated images (after v0.123.1). This causes failed deployments when trying to use newer versions like v0.124.1.
This PR updates the install examples in the documentation to:
`
ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s
`
as described in the [upgrading guidelines](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/UPGRADING.md).
=> [Docs] Update default collectorImage.repository in Helm chart examples due to DockerHub Image deprecation

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/values.yaml
Was there a reason to not release 0.125.0? If not, I would do this first and then continue with the release for:
- https://github.com/open-telemetry/opentelemetry-operator/pull/4021
cc @jaronoff97
=> Update OTEL Operator to v0.125.0 release

charts/opentelemetry-target-allocator/Chart.yaml, charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered/clusterRole.yaml, charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered/clusterRoleBinding.yaml, charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered/configmap.yaml, charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered/deployment.yaml, charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered/serviceAccount.yaml, charts/opentelemetry-target-allocator/examples/existing-service-account/rendered/configmap.yaml, charts/opentelemetry-target-allocator/examples/existing-service-account/rendered/deployment.yaml, charts/opentelemetry-target-allocator/examples/prometheus-scrape-config/rendered/clusterRole.yaml, charts/opentelemetry-target-allocator/examples/prometheus-scrape-config/rendered/clusterRoleBinding.yaml, charts/opentelemetry-target-allocator/examples/prometheus-scrape-config/rendered/configmap.yaml, charts/opentelemetry-target-allocator/examples/prometheus-scrape-config/rendered/deployment.yaml, charts/opentelemetry-target-allocator/examples/prometheus-scrape-config/rendered/serviceAccount.yaml, charts/opentelemetry-target-allocator/templates/_helpers.tpl, charts/opentelemetry-target-allocator/templates/deployment.yaml, charts/opentelemetry-target-allocator/values.schema.json, charts/opentelemetry-target-allocator/values.yaml
This PR:
* changes the default tag used by the target allocator image to use the appVersion if not set explicitly
* changes the tag used to pull the target allocator image to 0.126.0 from 0.123.0
* changes the version of the chart to 0.126.0 from 0.0.1 to match the release cycle of targetAllocator.
=> [charts/target-allocator] update to 0.126.0

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/clusterrole.yaml
Hi,
The operator tries to create multiple SubjectAccessReview at startup in order to test rights and enable/disable features dynamically such as RBAC creation (cf [this](https://github.com/open-telemetry/opentelemetry-operator/blob/a419080834a9f5e382652e795e499cd3689b0ff5/internal/config/config.go#L143)). Without this right all these features remain disabled.
Some error logs I was having:
```
{"level":"LEVEL(-2)","timestamp":"2025-05-25T19:34:46Z","logger":"config","message":"the rbac permissions are not set for the operator","reason":"unable to check rbac rules: subjectaccessreviews.authorization.k8s.io is forbidden: User \"system:serviceaccount:opentelemetry-operator:opentelemetry-operator\" cannot create resource \"subjectaccessreviews\" in API group \"authorization.k8s.io\" at the …
```
=> fix(opentelemetry-operator): allow rbac subjectaccessreviews

charts/opentelemetry-target-allocator/Chart.yaml, charts/opentelemetry-target-allocator/examples/collector-fleet/README.md, charts/opentelemetry-target-allocator/examples/collector-fleet/collectors.yaml, charts/opentelemetry-target-allocator/examples/collector-fleet/prometheus_example_pods.yaml, charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/clusterRole.yaml, charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/clusterRoleBinding.yaml, charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/configmap.yaml, charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/deployment.yaml, charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/service.yaml, charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/serviceAccount.yaml, charts/opentelemetry-target-allocator/examples/collector-fleet/values.yaml
Built on top of #1657 - this adds a bit more information on how you can realistically use the helm chart with a set of prometheus targets and collectors.
=> Example ta collector deployments

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/_helpers.tpl
There are multiple resources deployed by the otel operator that have the following required label
[app.kubernetes.io/version](http://app.kubernetes.io/version) . The label value must be below 63 char, defined [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set).
The image tag is being set in the opentelemetry operator  here - [https://github.com/open-telemetry/opentelemetry-helm-charts/blob/opentelemetry-ope[…]tor-0.76.0/charts/opentelemetry-operator/templates/_helpers.tpl](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/opentelemetry-operator-0.76.0/charts/opentelemetry-operator/templates/_helpers.tpl#L37)
and used in the label here - [https://github.com/open-telemetry/opentelemetry-helm-charts/blob/opentelemetry-ope[… …
=> Restrict operator version to 63 chars

charts/opentelemetry-operator/Chart.yaml, charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/deployment.yaml, charts/opentelemetry-operator/examples/default/rendered/role.yaml, charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/default/rendered/service.yaml, charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml, charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml, charts/opentelemetry-operator/templates/_helpers.tpl
There was a change in latest chart that truncated appVersion to 63 chars: https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1778. Since `"opentelemetry-operator.appVersion"` is also used to define `"opentelemetry-operator.image"`, this has an unintended side effect, where image tags were getting truncated. 
There is no max limit of tag length in OCI spec, so this can cause problems. It is also a common practice to specify digests as a part of tags like: `tag_name@sha256:digest_sha`, this gets truncated. 
This PR decouples `"opentelemetry-operator.image"` and `"opentelemetry-operator.appVersion"`.
=> fix: image tags longer than 63 chars getting truncated
