open-telemetry/opentelemetry-helm-charts

ct.yaml

bitnami is not being used in the chart

Remove redundant chart repo

---

.editorconfig

To have clean consistent formatting

Add .editorcofing

---

charts/opentelemetry-collector/.helmignore
charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/README.md
charts/opentelemetry-collector/templates/_helpers.tpl
charts/opentelemetry-collector/templates/_pod.tpl
charts/opentelemetry-collector/templates/config/_agent-config-override.tpl
charts/opentelemetry-collector/templates/config/_base.tpl
charts/opentelemetry-collector/templates/config/_metrics.tpl
charts/opentelemetry-collector/templates/config/_traces.tpl
charts/opentelemetry-collector/templates/configmap-agent.yaml
charts/opentelemetry-collector/templates/configmap.yaml
charts/opentelemetry-collector/templates/daemonset.yaml
charts/opentelemetry-collector/templates/deployment.yaml
charts/opentelemetry-collector/templates/hpa.yaml
charts/opentelemetry-collector/templates/service.yaml
charts/opentelemetry-collector/templates/serviceaccount.yaml
charts/opentelemetry-collector/values.schema.json
charts/opentelemetry-collector/values.yaml

The change was initially submitted and pre-reviewed in contrib repo: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1026

Add initial version of the opentelemetry-collector chart

---

.github/workflows/release.yaml

This is needed to fix the release pipeline

Remove adding unused dependancy in release workflow

---

charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/templates/service.yaml

There were some issues with multiple annotations, this tries to change the template to support them.

change service annotation template to support multiple annotations

---

.github/CODEOWNERS
CONTRIBUTING.md
README.md

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

Update community links to use main branch

---

.github/workflows/lint-test.yaml
.github/workflows/release.yaml
charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/values.yaml

also remove removed queued_retry
Signed-off-by: naseemkullah <naseem@transit.app>

update otel-collector to 0.19.0

---

.github/workflows/release.yaml
charts/opentelemetry-collector/Chart.yaml

remove ref to non-existing config cr.yaml
Signed-off-by: naseemkullah <naseem@transit.app>

fix release workflow

---

charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/README.md
charts/opentelemetry-collector/templates/_config.tpl
charts/opentelemetry-collector/templates/_pod.tpl
charts/opentelemetry-collector/values.yaml

Fixes https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2536

Add k8s container logs collection

---

charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/templates/_config.tpl

This PR follows [#2873 (collector-contrib)](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2873)

Strip wrapper off of filelog body

---

charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/templates/_config.tpl

Follows [#88 (opentelemetry-log-collection)](https://github.com/open-telemetry/opentelemetry-log-collection/pull/88) and [#3017 (opentelemetry-collector-contrib)](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3017)

Rename log 'record' to 'body'

---

.github/workflows/lint-test.yaml

The old version of kind started timing out on cluster creation. The new one is working well

Upgrade helm/kind-action

---

charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/ci/standalone-collector-values.yaml

This test case will be failing until kind action is upgraded https://github.com/open-telemetry/opentelemetry-helm-charts/pull/53

Add a test case for standalone collector deployment

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/templates/admission-webhooks/validatingwebhookconfiguration.yaml
charts/opentelemetry-operator/values.yaml

This PR bumps the OTEL Operator version to v0.31.0.
cc @alolita @dmitryax

Bump OTEL Operator version to v0.31.0

---

charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/values.yaml

This is a breakout PR of #97 
Fixes #94

fix(collector): explicitly add otlp endpoints and expose otlp-http

---

.github/workflows/lint-test.yaml
charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/crds/crd-opentelemetryinstrumentation.yaml
charts/opentelemetry-operator/release/kuttl-test.yaml
charts/opentelemetry-operator/templates/admission-webhooks/mutatingwebhookconfiguration.yaml
charts/opentelemetry-operator/templates/admission-webhooks/validatingwebhookconfiguration.yaml
charts/opentelemetry-operator/templates/certmanager.yaml
charts/opentelemetry-operator/templates/clusterrole.yaml
charts/opentelemetry-operator/values.yaml

**Note**: A new CRD has been introduced in otel operator to support auto-instrumentation with otel operator deployments. 
Also, I'm one of the maintainers of Otel-Operator and an active user of the otel-operator helm chart. I would love to collaborate in the active development of these helm charts.

Update Otel Operator to v0.41.0 release

---

charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/templates/pdb.yaml
charts/opentelemetry-collector/values.yaml

Add option for PodDisruptionBudget(pdb) to opentelemetry-collector

Add option for PodDisruptionBudget

---

charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/templates/_helpers.tpl
charts/opentelemetry-collector/templates/ingress.yaml
charts/opentelemetry-collector/values.yaml

Allows to deploy an ingress object for the collector service
Fixes #76

feat(collector): allow deployment of ingress for standaloneCollector

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/templates/deployment.yaml
charts/opentelemetry-operator/values.yaml

Please check additional information in commit messages

Scheduling controls

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/templates/deployment.yaml
charts/opentelemetry-operator/values.yaml

added host network flag for webhook

added hostNetwork true for operator for webhook

---

charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml
charts/opentelemetry-collector/templates/NOTES.txt

Update NOTES.txt to properly display warnings

---

charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml
charts/opentelemetry-collector/templates/NOTES.txt

Remove S from extraVolumeMounts in [documentation](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/7a9309da0b47eae2853c010fd4ee8e45cb9999f3/charts/opentelemetry-collector/templates/NOTES.txt#L10)

docs: Remove S from extraVolumeMounts

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/release/go.mod
charts/opentelemetry-operator/release/go.sum

operator: upgrade go dependancies in release module

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/templates/deployment.yaml
charts/opentelemetry-operator/templates/service.yaml

Addresses https://github.com/open-telemetry/opentelemetry-helm-charts/issues/243

prevent unused resources creation when admissionWebhooks are disabled

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/templates/deployment.yaml
charts/opentelemetry-operator/values.yaml

Resolves https://github.com/open-telemetry/opentelemetry-helm-charts/issues/250

[operator] Add extraArgs option to manager

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/templates/_helpers.tpl
charts/opentelemetry-operator/templates/deployment.yaml
charts/opentelemetry-operator/templates/service.yaml
charts/opentelemetry-operator/templates/servicemonitor.yaml
charts/opentelemetry-operator/values.yaml

https://github.com/open-telemetry/opentelemetry-helm-charts/issues/252

Add support for ServiceMonitor

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/templates/_helpers.tpl
charts/opentelemetry-operator/templates/clusterrolebinding.yaml
charts/opentelemetry-operator/templates/rolebinding.yaml
charts/opentelemetry-operator/templates/serviceaccount.yaml
charts/opentelemetry-operator/values.yaml

https://github.com/open-telemetry/opentelemetry-helm-charts/issues/257

Make ServiceAccount configurable

---

charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml

The PR bumps the default collector version to 0.54.0.  Reading through Contrib and Core Release notes I did not see any breaking changes.

Bump collector version to 0.54.0

---

charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml
charts/opentelemetry-collector/values.schema.json

fix: https://github.com/open-telemetry/opentelemetry-helm-charts/issues/228

add `enabled` in values.schema.json

---

charts/opentelemetry-collector/Chart.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/configmap.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/deployment.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/service.yaml
charts/opentelemetry-collector/examples/daemonset-and-deployment/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-collector-logs/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-hostmetrics/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-lifecycle-hooks/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/daemonset-only/rendered/configmap-agent.yaml
charts/opentelemetry-collector/examples/daemonset-only/rendered/daemonset.yaml
charts/opentelemetry-collector/examples/daemonset-only/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/configmap.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/deployment.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/service.yaml
charts/opentelemetry-collector/examples/deployment-only/rendered/serviceaccount.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/configmap.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/deployment.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/service.yaml
charts/opentelemetry-collector/examples/deployment-otlp-traces/rendered/serviceaccount.yaml

The PR bumps the default collector version to 0.55.0. Reading through Contrib and Core Release notes I did not see any breaking changes.

Bump collector version to 0.55.0

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/templates/deployment.yaml
charts/opentelemetry-operator/values.yaml

Addresses https://github.com/open-telemetry/opentelemetry-helm-charts/issues/275

[opentelemetry-operator] - Add support for imagePullSecrets

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/templates/role.yaml
charts/opentelemetry-operator/templates/rolebinding.yaml
charts/opentelemetry-operator/values.yaml

Addresses https://github.com/open-telemetry/opentelemetry-helm-charts/issues/277

Make roles creation optional

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

Addresses https://github.com/open-telemetry/opentelemetry-helm-charts/issues/136

Introduce values schema for the operator chart

---

.github/workflows/operator-test.yaml
charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/crds/crd-opentelemetryinstrumentation.yaml
charts/opentelemetry-operator/values.yaml

Addresses https://github.com/open-telemetry/opentelemetry-helm-charts/issues/296

[opentelemetry-operator] - BUMP to version 0.56.0

---

README.md
charts/opentelemetry-operator/Chart.yaml

Proposal to add @Allex1 as an approver for opentelemetry-helm-charts.
Alex has been a driving force for the operator chart and helps review PRs across the repo.
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/297
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/289
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/285
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/278
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/276
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/268
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/266
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/265
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/258 …

Add Allex1 as an approver

---

.github/CODEOWNERS

Adds sections to the code owners file for the 3 different charts

[chore] Update codeowners file

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/templates/deployment.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

Related to https://github.com/open-telemetry/opentelemetry-helm-charts/issues/305

Run non-root containers in the manager pod

---

README.md

Moving @naseemkullah to Emeritus Approvers given that there is no recent activity.
@naseemkullah please let us know if you intend to contribute to this repo going forward. I'm happy to close the PR

Move Naseem Ullah to Emeritus Approvers list

---

.github/dependabot.yml

No more go code in this repo :)

Remove go dependancies from dependabot config

---

CONTRIBUTING.md
charts/opentelemetry-operator/CONTRIBUTING.md
charts/opentelemetry-operator/Chart.yaml

Adds brief contributing guide for the operator chart.

[opentelemetry-operator] Add operator contrib guide

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/templates/clusterrole.yaml
charts/opentelemetry-operator/templates/clusterrolebinding.yaml
charts/opentelemetry-operator/templates/deployment.yaml
charts/opentelemetry-operator/templates/service.yaml
charts/opentelemetry-operator/templates/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.yaml

Addresses https://github.com/open-telemetry/opentelemetry-helm-charts/issues/353

Make kubeRBACProxy optional

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

[opentelemetry-operator] - BUMP operator to 0.60.0

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/templates/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/templates/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

Signed-off-by: Jared Tan <jian.tan@daocloud.io>

[operator] polish testframework image schema

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

We have had the needs to change those values ourselves, so I figured I would make a PR for this

[opentelemetry-operator] add timeoutSeconds and selector values for admission webhooks

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/README.md
charts/opentelemetry-operator/UPGRADING.md
charts/opentelemetry-operator/templates/NOTES.txt
charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook.yaml
charts/opentelemetry-operator/templates/certmanager.yaml
charts/opentelemetry-operator/templates/deployment.yaml
charts/opentelemetry-operator/templates/service.yaml
charts/opentelemetry-operator/templates/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

Addresses https://github.com/open-telemetry/opentelemetry-helm-charts/issues/410

[operator] Allow byo webhooks and cert

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/jaeger.yaml

Fixes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/426
There are errors coming from recommendation service for me using the current version as well as this version. Need to investigate.

[opentelemetry-demo] Update demo chart to 0.6.0-beta

---

.github/actions/setup/action.yaml
.github/workflows/release.yaml

Addresses https://github.com/open-telemetry/opentelemetry-helm-charts/pull/479

[chore] bump setup-helm action

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/jaeger.yaml
charts/opentelemetry-demo/templates/_helpers.tpl

Addressing #466 to add a label to all services

[demo] Adding app.kubernetes.io/part-of to all components

---

.github/actions/setup/action.yaml
.github/workflows/release.yaml

Adds prometheus and grafana charts to the release action

[chore] add missing chart dependencies

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/templates/clusterrole.yaml

Related to https://github.com/open-telemetry/opentelemetry-operator/issues/1202

Trim unnecessary otelcol operator verbs

---

.github/CODEOWNERS
charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/jaeger.yaml

Adds @puckpuck as demo chart code owner.  Removes @wph95.  @wph95 if you'd like to be added back as a demo chart code owner please start contributing to the demo chart again.

[opentelemetry-demo] Update demo chart codeowners

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/templates/deployment.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

add ability to add extra config for kube-rbac-proxy

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/jaeger.yaml
charts/opentelemetry-demo/templates/NOTES.txt

Load generator ui link was not correct

fix typo in NOTES.txt

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/README.md
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/_helpers.tpl
charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook.yaml
charts/opentelemetry-operator/templates/certmanager.yaml
charts/opentelemetry-operator/templates/clusterrole.yaml
charts/opentelemetry-operator/templates/clusterrolebinding.yaml
charts/opentelemetry-operator/templates/deployment.yaml
charts/opentelemetry-operator/templates/role.yaml
charts/opentelemetry-operator/templates/rolebinding.yaml
charts/opentelemetry-operator/templates/service.yaml
charts/opentelemetry-operator/templates/serviceaccount.yaml
charts/opentelemetry-operator/templates/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/templates/tests/test-service-connection.yaml

[opentelmetry-operator] Use labels and selector labels from helpers

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/deployment.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

[opentelemetry-operator] Improve Operator deployment args templating

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

BUMP operator/collector to v0.66.0

[operator] - BUMP operator/collector to v0.66.0

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana/configmap.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana/deployment.yaml
charts/opentelemetry-demo/values.yaml

Fixed the datasource URL for the Jaeger within Grafana configmap.

Fix Grafana datasource for Jaeger.

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

[operator] - Bump kube-rbac-proxy 0.13.0

---

.github/actions/setup/action.yaml
.github/workflows/release.yaml

replaces https://github.com/open-telemetry/opentelemetry-helm-charts/pull/568

[chore] bump helm action

---

.github/workflows/operator-test.yaml
charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/clusterrole.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

[BUMP] - operator 0.67/collector 0.68

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/README.md
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml

Updates Demo chart's readme to specify lack of Apple Silicon support.
Relates to https://github.com/open-telemetry/opentelemetry-helm-charts/issues/580

[chore] Call out demo chart's inability to run on Apple Silicon

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/values.yaml

Add `service.instance.id` with a value of pod name to the default `OTEL_RESOURCE_ATTRIBUTES` env var 
Resolves #600

[demo] Add service.instance.id

---

.github/CODEOWNERS
README.md

@povilasv has been doing great work with us over the last couple months, contributing to many PRs, working issues, and providing reviews.
@povilasv if there is any additional info you'd like added to your entry please let me know

Promote povilasv to Approver

---

.github/workflows/operator-test.yaml
charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/UPGRADING.md
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook.yaml
charts/opentelemetry-operator/templates/certmanager.yaml
charts/opentelemetry-operator/templates/clusterrole.yaml
charts/opentelemetry-operator/templates/clusterrolebinding.yaml
charts/opentelemetry-operator/templates/deployment.yaml
charts/opentelemetry-operator/templates/role.yaml
charts/opentelemetry-operator/templates/rolebinding.yaml
charts/opentelemetry-operator/templates/service.yaml
charts/opentelemetry-operator/templates/serviceaccount.yaml
charts/opentelemetry-operator/templates/servicemonitor.yaml
charts/opentelemetry-operator/templates/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/templates/tests/test-service-connection.yaml

Closes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/612

[opentelemetry-operator] Use fullname instead of name for objects

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetryinstrumentation.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

[BUMP] - operator 0.69/collector 0.71

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/deployment.yaml
charts/opentelemetry-operator/templates/pdb.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

hello,
with this PR I'd like to introduce PodDisruptionBudget configuration to otel-operator itself.

add PodDisruptionBudget to otel-operator

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/serviceaccount.yaml

Close https://github.com/open-telemetry/opentelemetry-helm-charts/issues/628.
split PR(https://github.com/open-telemetry/opentelemetry-helm-charts/pull/671) for each charts. This PR is for opentelemetry-operator chart.

[operator] Define annotations in consistent way

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/verticalpodautoscaler.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

Also regenerated schema like described in [HERE](https://www.arthurkoziel.com/validate-helm-chart-values-with-json-schemas/) as it was inconsistent

[operator] - Add verticalpodautoscaler support for manager

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml
charts/opentelemetry-demo/templates/serviceaccount.yaml

Close https://github.com/open-telemetry/opentelemetry-helm-charts/issues/628.
split PR(https://github.com/open-telemetry/opentelemetry-helm-charts/pull/671) for each charts. This PR is for opentelemetry-demo chart.

[demo] Define annotations in consistent way

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/crds/crd-opentelemetryinstrumentation.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/clusterrole.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

Should be merged after https://github.com/open-telemetry/opentelemetry-helm-charts/pull/678

[BUMP] - operator 0.73/collector 0.74

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/README.md
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml
charts/opentelemetry-demo/values.yaml

This documents the `initContainers` construct added for demo components in #685

[demo] document initContainers

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml
charts/opentelemetry-demo/values.schema.json

[demo] define proper SecurityContext and LivenessProbe schemas

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/verticalpodautoscaler.yaml

missed it in the previous pr 😞

[operator] - fix vpa targetRef name

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

Also manually fixed the PDB regression mentioned in https://github.com/open-telemetry/opentelemetry-helm-charts/pull/678 by @avoidik until we identify an automated way.

[BUMP] - operator 0.74/collector 0.75

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

Addresses https://github.com/open-telemetry/opentelemetry-helm-charts/issues/736

[BUMP] - kube-rbac-proxy v0.14.1

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/verticalpodautoscaler.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

Addresses https://github.com/open-telemetry/opentelemetry-helm-charts/issues/739

Allow setting minReplicas in Operator VPA

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

Addresses https://github.com/open-telemetry/opentelemetry-helm-charts/issues/758

[BUMP] - operator 0.75

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/templates/admission-webhooks/operator-webhook.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

Relates to [opentelemetry-operator#1765](https://github.com/open-telemetry/opentelemetry-operator/issues/1765)

feat: Introduce Customizable Pod Admission FailurePolicy

---

.github/workflows/operator-test.yaml
charts/opentelemetry-operator/CONTRIBUTING.md
charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/crds/crd-opentelemetryinstrumentation.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.yaml

Upgrade operator to v0.78.0

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.yaml

[operator] - BUMP operator/collector to v0.79.0

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/crds/crd-opentelemetryinstrumentation.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

Reviewing the operator release notes I don't see anything that affects the chart.

[operator] bump default operator version to 0.80.0

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/README.md
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml

+ Add link to logging exporter

Add new helm command to README.md, fix typos

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/clusterrole.yaml

Fixes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/859

[operator] Update clusterrole

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml
charts/opentelemetry-demo/grafana-dashboards/demo-dashboard.json
charts/opentelemetry-demo/grafana-dashboards/opentelemetry-collector.json

Updates Grafana dashboards in the demo based on the changes in this [demo repo PR](https://github.com/open-telemetry/opentelemetry-demo/pull/1150)

(demo): update grafana dashboards

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/templates/tests/test-service-connection.yaml

Fix for https://github.com/open-telemetry/opentelemetry-helm-charts/issues/910

[opentelemetry-operator] Add affinity, tolerations and nodeSelector to tests

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/clusterrole.yaml
charts/opentelemetry-operator/values.yaml

Needed for correct operation after installing manager `v0.86.0` due to
https://github.com/open-telemetry/opentelemetry-operator/pull/2141/

[operator] bump to 0.86.0

---

.github/actions/setup/action.yaml
.github/kind-1.24.yaml
charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

Operator v0.89.0/kube-rbac-proxy v0.15.0 and regenerated values schema

[BUMP] Operator v0.89.0/kube-rbac-proxy v0.15.0

---

README.md

@JaredTan95 has been a big help with all the helm charts recently, reviewing PRs and contributing improvements.
@JaredTan95 if there is any additional info you'd like added to your entry or a specific chart you'd like added to in CODEOWNERS please let me know.

Promote JaredTan95 to Approver

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.yaml

Closes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/992

[operator] bump collector version to 0.92.0

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml
charts/opentelemetry-demo/templates/grafana-dashboards.yaml

demo: add missing namespace on grafana dashboard

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/clusterrole.yaml
charts/opentelemetry-operator/values.schema.json

closes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/997

[operator] Bump operator version to 0.92.1

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/opentelemetry-collector/configmap-agent.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/opentelemetry-collector/daemonset.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/opentelemetry-collector/configmap.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/opentelemetry-collector/deployment.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/opentelemetry-collector/configmap.yaml
charts/opentelemetry-demo/examples/default/rendered/opentelemetry-collector/deployment.yaml
charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/opentelemetry-collector/configmap-agent.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/opentelemetry-collector/daemonset.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/opentelemetry-collector/configmap.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/opentelemetry-collector/deployment.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml
charts/opentelemetry-demo/values.yaml

closes: https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1031

Fixed changed connectors.spanmetrics config, closes #1031

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml
charts/opentelemetry-demo/values.schema.json

Specifying seccompProfile in securityContext fail validation, this PR adds seccompProfile to the values schema

[demo] Add seccompProfile property to securityContext

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/README.md
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml

Update Operator README.md

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml
charts/opentelemetry-demo/grafana-dashboards/opentelemetry-collector-data-flow.json

https://github.com/open-telemetry/opentelemetry-demo/pull/1465

fix failed_spans typo in grafana dashboards

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.schema.json

close https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1089

[operator] support install otel-operator as subchart

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/README.md
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml

Closes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1088

[operator] Fix readme

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.yaml

Bringing it in line with the operator.

[operator] Bump collector version to 0.96.0

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/certmanager.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

override k8s default cluster domain (cluster.local)

[operator] new value for k8s cluster domain

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/crds/crd-opentelemetry.io_opampbridges.yaml
charts/opentelemetry-operator/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/crds/crd-opentelemetryinstrumentation.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/clusterrole.yaml
charts/opentelemetry-operator/values.yaml

completes operator release for 0.97.0

[opentelemetry-operator] bump to 0.97.0

---

charts/opentelemetry-kube-stack/Chart.yaml
charts/opentelemetry-kube-stack/templates/_helpers.tpl
charts/opentelemetry-kube-stack/templates/clusterrole.yaml
charts/opentelemetry-kube-stack/templates/collector.yaml
charts/opentelemetry-kube-stack/templates/instrumentation.yaml
charts/opentelemetry-kube-stack/values.schema.json
charts/opentelemetry-kube-stack/values.yaml

Closes #1078 by providing a method for creating a single instrumentation resource

Add instrumentation to chart

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/README.md
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml

Fixes https://github.com/open-telemetry/opentelemetry-demo/issues/1497
Fixes https://github.com/open-telemetry/opentelemetry-demo/issues/1499
Add additional permission to the service account.

Additional permissions for OpenShift installation

---

.github/workflows/operator-test.yaml
charts/opentelemetry-operator/Chart.yaml

Skip flaky test https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1180

[operator] Skip flaky test

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/conf/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.yaml

Related to https://github.com/open-telemetry/opentelemetry-operator/issues/2983

[operator] bump default version to 0.101.0

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/certmanager.yaml
charts/opentelemetry-operator/values.schema.json
charts/opentelemetry-operator/values.yaml

closes #1227 by enabling the chart's Certificate to be customized for duration and renewBefore

Enable customization for duration and renewbefore for operator Certificate

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml
charts/opentelemetry-demo/values.yaml

Fixes [this](https://github.com/open-telemetry/opentelemetry-demo/issues/1663) issue in the demo repo.

[demo] increase accountingservice memory

---

charts/opentelemetry-kube-stack/Chart.yaml
charts/opentelemetry-kube-stack/charts/crds/README.md
charts/opentelemetry-kube-stack/charts/crds/crds/monitoring.coreos.com_podmonitors.yaml
charts/opentelemetry-kube-stack/charts/crds/crds/monitoring.coreos.com_servicemonitors.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml
charts/opentelemetry-kube-stack/examples/targetallocator-prom/rendered/collector.yaml

Adds the prometheus CRDs to the chart which will be used for the kube-prometheus-stack

Add Prometheus CRDs to otel-kube-stack

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/README.md
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml

fixes #1333
I believe the main change is the use of [structured config](https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/crd-changelog.md#structured-configuration). I've updated the readme based on that upgrade example, but haven't actually applied the updated examples to verify that they are valid.

Update examples for v1beta1

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml

We broke main by merging 2 demo PRs with the same chart version:
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1326
- https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1327

[demo] update demo version to fix main

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.yaml

bumps the operator chart to match the latest release version (i should have done this post release but forgot :/)

[chore] bump operator to 109

---

charts/opentelemetry-kube-stack/Chart.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml
charts/opentelemetry-kube-stack/templates/collector.yaml

Fix volume and mount indentation

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/UPGRADING.md
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml

Adds a note to UPGRADING.MD about Demo upgrade support.
related to this [PR](https://github.com/open-telemetry/opentelemetry.io/pull/5655) in docs

[demo] clarify upgrades

---

charts/opentelemetry-kube-stack/Chart.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/kubelet_scrape_configs.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml

The previous example was broken because of an escaping issue.

Update kubelet_scrape_config example

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/conf/crds/crd-opentelemetry.io_opampbridges.yaml
charts/opentelemetry-operator/conf/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/conf/crds/crd-opentelemetryinstrumentation.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.yaml

Operator v0.116.0
collector v0.116.1

[operator] - Release v0.116.0

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/conf/crds/crd-opentelemetry.io_opampbridges.yaml
charts/opentelemetry-operator/conf/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/conf/crds/crd-opentelemetryinstrumentation.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.yaml

As per https://github.com/open-telemetry/opentelemetry-operator/issues/3599.

[operator] Release v0.117.0

---

charts/opentelemetry-kube-stack/Chart.yaml
charts/opentelemetry-kube-stack/README.md
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml

Updated documentation for external scrape_configs_file

---

charts/opentelemetry-demo/Chart.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/component.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/bring-your-own-observability/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/component.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/collector-as-daemonset/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/component.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/custom-environment-variables/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/default/rendered/component.yaml
charts/opentelemetry-demo/examples/default/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/default/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/component.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/kubernetes-infra-monitoring/rendered/serviceaccount.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/component.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/flagd-config.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/grafana-dashboards.yaml
charts/opentelemetry-demo/examples/public-hosted-ingress/rendered/serviceaccount.yaml
charts/opentelemetry-demo/values.yaml

Closes https://github.com/open-telemetry/opentelemetry-demo/issues/1831

Add note for frontend proxy memory limit

---

CONTRIBUTING.md

This PR is part of [Contributing guide to repos #31](https://github.com/open-telemetry/sig-contributor-experience/issues/31)
And all details are contained there.
Places marked "TBD" require info from maintainers to be complete. Please feel free to edit where needed.
This PR sets the groundwork for a comprehensive guide, enabling maintainers to contribute essential details. Once complete, this document will serve as a critical resource for future contributors, following a consistent pattern across other OTel repos.

Improve Contributor Guide

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/conf/crds/crd-opentelemetry.io_targetallocators.yaml
charts/opentelemetry-operator/conf/crds/crd-opentelemetrycollector.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.yaml

Closes https://github.com/open-telemetry/opentelemetry-operator/issues/3861

[operator]: update default operator to v0.122.0

---

charts/opentelemetry-kube-stack/Chart.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml
charts/opentelemetry-kube-stack/templates/bridge.yaml
charts/opentelemetry-kube-stack/values.schema.json
charts/opentelemetry-kube-stack/values.yaml

I want to deploy an OpAMPBridge using this chart, but it appears there is no way to add NonIdentifyingAttributes, so I have added this.
support: https://github.com/open-telemetry/opentelemetry-operator/pull/3799/files#diff-cb1f96fe3fb777a2c197802f26b7066ac0105ee8408db0f6d0e45d7a4f0883baR98-R101

add OpAMPBridge Spec description

---

.github/workflows/operator-test.yaml
charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.yaml

Part of https://github.com/open-telemetry/opentelemetry-operator/issues/3865.

[operator] Bump version to 0.123.0

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.yaml

Part of https://github.com/open-telemetry/opentelemetry-operator/issues/3907.

[operator] Bump version to 0.124.0

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml

I merged something and forgot to check it had the latest from main: https://github.com/open-telemetry/opentelemetry-helm-charts/actions/runs/14931083927/job/41947256025

fix(operator): fix chart version

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/templates/clusterrole.yaml

[operator] Add in new permissions

---

charts/opentelemetry-operator/Chart.yaml
charts/opentelemetry-operator/examples/default/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/default/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/default/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/deployment.yaml
charts/opentelemetry-operator/examples/default/rendered/role.yaml
charts/opentelemetry-operator/examples/default/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/default/rendered/service.yaml
charts/opentelemetry-operator/examples/default/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/default/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/admission-webhooks/operator-webhook-with-cert-manager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/certmanager.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrole.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/clusterrolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/deployment.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/role.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/rolebinding.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/service.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/serviceaccount.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-certmanager-connection.yaml
charts/opentelemetry-operator/examples/feature-gates/rendered/tests/test-service-connection.yaml
charts/opentelemetry-operator/values.schema.json

Replaces https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1803 and https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1804

[opentelemetry-operator] Fix values.schema.json

---

Makefile
charts/opentelemetry-target-allocator/Chart.yaml
charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/clusterRole.yaml
charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/clusterRoleBinding.yaml
charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/configmap.yaml
charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/deployment.yaml
charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/serviceAccount.yaml
charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered/clusterRole.yaml
charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered/clusterRoleBinding.yaml
charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered/configmap.yaml
charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered/deployment.yaml
charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered/serviceAccount.yaml
charts/opentelemetry-target-allocator/examples/existing-service-account/rendered/configmap.yaml
charts/opentelemetry-target-allocator/examples/existing-service-account/rendered/deployment.yaml
charts/opentelemetry-target-allocator/examples/prometheus-scrape-config/rendered/clusterRole.yaml
charts/opentelemetry-target-allocator/examples/prometheus-scrape-config/rendered/clusterRoleBinding.yaml
charts/opentelemetry-target-allocator/examples/prometheus-scrape-config/rendered/configmap.yaml
charts/opentelemetry-target-allocator/examples/prometheus-scrape-config/rendered/deployment.yaml
charts/opentelemetry-target-allocator/examples/prometheus-scrape-config/rendered/serviceAccount.yaml
charts/opentelemetry-target-allocator/values.schema.json

Fixes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1743

[opentelemetry-target-allocator] support for `global` and `enabled` in `values.schema.json`

---

charts/opentelemetry-kube-stack/Chart.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml
charts/opentelemetry-kube-stack/examples/isolated-multicollector-deployment/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/isolated-multicollector-deployment/rendered/hooks.yaml
charts/opentelemetry-kube-stack/examples/no-leader-election-extension/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/no-leader-election-extension/rendered/hooks.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml
charts/opentelemetry-kube-stack/examples/secrets-csi-driver/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/secrets-csi-driver/rendered/hooks.yaml
charts/opentelemetry-kube-stack/values.yaml

- closes https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1865

[kube-stack]: use a specific kubectl image version

---

charts/opentelemetry-kube-stack/Chart.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/bridge.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/hooks.yaml
charts/opentelemetry-kube-stack/examples/cloud-demo/rendered/instrumentation.yaml
charts/opentelemetry-kube-stack/examples/isolated-multicollector-deployment/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/isolated-multicollector-deployment/rendered/hooks.yaml
charts/opentelemetry-kube-stack/examples/no-leader-election-extension/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/no-leader-election-extension/rendered/hooks.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-api-server/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-controller-manager/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-dns/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-etcd/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-proxy/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/service.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/exporters/kube-scheduler/servicemonitor.yaml
charts/opentelemetry-kube-stack/examples/prometheus-otel/rendered/hooks.yaml
charts/opentelemetry-kube-stack/examples/secrets-csi-driver/rendered/collector.yaml
charts/opentelemetry-kube-stack/examples/secrets-csi-driver/rendered/hooks.yaml
charts/opentelemetry-kube-stack/templates/_config.tpl

fix(opentelemetry-kube-stack): correct container name for collector logs exclusion

---

charts/opentelemetry-target-allocator/Chart.yaml
charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/clusterRole.yaml
charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/clusterRoleBinding.yaml
charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/configmap.yaml
charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/deployment.yaml
charts/opentelemetry-target-allocator/examples/collector-fleet/rendered/serviceAccount.yaml
charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered/clusterRole.yaml
charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered/clusterRoleBinding.yaml
charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered/configmap.yaml
charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered/deployment.yaml
charts/opentelemetry-target-allocator/examples/consistent-hashing/rendered/serviceAccount.yaml
charts/opentelemetry-target-allocator/examples/existing-service-account/rendered/configmap.yaml
charts/opentelemetry-target-allocator/examples/existing-service-account/rendered/deployment.yaml
charts/opentelemetry-target-allocator/examples/prometheus-scrape-config/rendered/clusterRole.yaml
charts/opentelemetry-target-allocator/examples/prometheus-scrape-config/rendered/clusterRoleBinding.yaml
charts/opentelemetry-target-allocator/examples/prometheus-scrape-config/rendered/configmap.yaml
charts/opentelemetry-target-allocator/examples/prometheus-scrape-config/rendered/deployment.yaml
charts/opentelemetry-target-allocator/examples/prometheus-scrape-config/rendered/serviceAccount.yaml
charts/opentelemetry-target-allocator/templates/extramanifests.yaml
charts/opentelemetry-target-allocator/values.yaml

Follow-up of https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1850

feat(target-allocator): support extraObjects
